In [1]:
from IPython.display import HTML, display

# Load Google Fonts for premium typography
display(HTML('<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@300;400;500&family=Source+Sans+3:wght@300;400;500;600&display=swap" rel="stylesheet">'))

# Hide this code cell after execution so only the visual output shows
display(HTML('<style>.jp-Cell.jp-CodeCell:has(.cell-cover-output) .jp-Cell-inputWrapper,\
.cell.code_cell:has(.cell-cover-output) .input{display:none !important;}</style>'))

display(HTML("""
<div class="cell-cover-output" style="
    background: linear-gradient(145deg, #f5eeff 0%, #e8d6f7 40%, #d4b8ee 70%, #ede0fa 100%);
    border-radius: 24px;
    padding: 56px 48px 48px;
    position: relative;
    overflow: hidden;
    box-shadow: 0 30px 80px rgba(74,31,138,0.25), 0 8px 24px rgba(0,0,0,0.15);
    max-width: 780px;
    margin: auto;
    font-family: 'Source Sans 3', sans-serif;
">

    <!-- Ambient light: top-right white glow on outer panel -->
    <div style="position:absolute; top:0; right:0; bottom:0; left:0;
        background:
            radial-gradient(ellipse 60% 50% at 90% 10%, rgba(255,255,255,0.55) 0%, transparent 60%),
            radial-gradient(ellipse 40% 40% at 5% 90%, rgba(190,159,225,0.3) 0%, transparent 60%);
        pointer-events:none;">
    </div>

    <!-- Decorative orb: top-right -->
    <div style="position:absolute; width:180px; height:180px; top:-60px; right:-50px;
        border-radius:50%;
        background: radial-gradient(circle, rgba(107,47,175,0.12) 0%, transparent 70%);
        border:1px solid rgba(107,47,175,0.08); pointer-events:none;">
    </div>

    <!-- Decorative orb: bottom-right -->
    <div style="position:absolute; width:120px; height:120px; bottom:60px; right:40px;
        border-radius:50%;
        background: radial-gradient(circle, rgba(190,159,225,0.10) 0%, transparent 70%);
        border:1px solid rgba(190,159,225,0.12); pointer-events:none;">
    </div>

    <!-- Decorative orb: mid-left -->
    <div style="position:absolute; width:80px; height:80px; top:50%; left:-20px;
        border-radius:50%;
        background: radial-gradient(circle, rgba(107,47,175,0.08) 0%, transparent 70%);
        pointer-events:none;">
    </div>

    <!-- Top accent bar -->
    <div style="position:absolute; top:0; left:0; right:0; height:3px;
        background: linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);
    "></div>

    <!-- Header — all centered -->
    <div style="text-align:center; margin-bottom:36px; position:relative;">
        <p style="font-family:'Source Sans 3',sans-serif; font-size:10px; font-weight:600;
            letter-spacing:7px; text-transform:uppercase; color:#7b4db5; margin:0 0 18px 0;
            text-align:center;">
            Week 3 Project &nbsp;|&nbsp; Data Cleaning &amp; Preparation
        </p>
        <h1 style="font-family:'Playfair Display',serif; font-size:52px; font-weight:400;
            color:#2a0f5e; letter-spacing:3px; line-height:1.1; margin:0 0 10px 0;
            text-align:center;">
            Employee <span style="font-weight:400; color:#6b2faf;">Data</span><br>Cleaning
        </h1>
        <p style="font-family:'Source Sans 3',sans-serif; font-size:11px; letter-spacing:6px;
            text-transform:uppercase; color:#9b70cc; margin:0;
            text-align:center;">
            Comprehensive Report
        </p>
        <div style="width:60px; height:1px;
            background: linear-gradient(90deg, transparent, rgba(107,47,175,0.4), transparent);
            margin:24px auto;">
        </div>
    </div>

    <!-- Info Card — HD Realism version -->
    <div style="
        background:
            radial-gradient(ellipse at 15% 10%, rgba(180,150,230,0.14) 0%, transparent 50%),
            radial-gradient(ellipse at 85% 90%, rgba(90,50,150,0.10) 0%, transparent 50%),
            radial-gradient(ellipse at 50% 50%, rgba(140,100,210,0.06) 0%, transparent 60%),
            linear-gradient(150deg,
                #6b3fa0 0%,
                #7344a8 10%,
                #7b4db5 25%,
                #8254bc 38%,
                #8a5ac2 50%,
                #8254bc 62%,
                #7b4db5 75%,
                #7344a8 90%,
                #7040aa 100%);
        border-radius:16px;
        padding:36px 40px;
        border:1px solid rgba(255,255,255,0.18);
        box-shadow:
            0 30px 70px rgba(74,31,138,0.40),
            0 12px 28px rgba(0,0,0,0.20),
            0 4px 10px rgba(74,31,138,0.15),
            inset 0 1px 0 rgba(255,255,255,0.18),
            inset 0 -1px 0 rgba(0,0,0,0.12);
        position:relative;
        overflow:hidden;
    ">

        <!-- Card inner glow: top-right light spill -->
        <div style="position:absolute; top:-30px; right:-30px; width:200px; height:200px;
            background: radial-gradient(circle, rgba(200,175,240,0.12) 0%, transparent 70%);
            border-radius:50%; pointer-events:none;">
        </div>

        <!-- Card inner glow: bottom-left depth anchor -->
        <div style="position:absolute; bottom:-25px; left:-25px; width:170px; height:170px;
            background: radial-gradient(circle, rgba(90,50,150,0.08) 0%, transparent 70%);
            border-radius:50%; pointer-events:none;">
        </div>

        <!-- Shine line at top edge -->
        <div style="position:absolute; top:0; left:20px; right:20px; height:1px;
            background: linear-gradient(90deg, transparent, rgba(255,255,255,0.20) 25%, rgba(255,255,255,0.38) 50%, rgba(255,255,255,0.20) 75%, transparent);
        "></div>

        <!-- Group -->
        <p style="font-family:'Source Sans 3',sans-serif; font-size:9px; font-weight:600;
            letter-spacing:5px; text-transform:uppercase; color:rgba(255,255,255,0.6); margin:0 0 10px 0;
            position:relative;">
            Group
        </p>
        <div style="display:inline-flex; align-items:center; gap:10px;
            background:rgba(255,255,255,0.12); border:1px solid rgba(255,255,255,0.25);
            border-radius:8px; padding:8px 18px; margin-bottom:24px; position:relative;">
            <div style="width:6px; height:6px; border-radius:50%; background:#fff;
                box-shadow:0 0 8px rgba(255,255,255,0.7);"></div>
            <span style="font-family:'Source Sans 3',sans-serif; font-size:18px; font-weight:700;
                letter-spacing:6px; color:#ffffff;">EXCEL</span>
        </div>

        <!-- Divider -->
        <div style="height:1px; background:linear-gradient(90deg, rgba(255,255,255,0.2), rgba(255,255,255,0.05));
            margin-bottom:24px;"></div>

        <!-- Members -->
        <p style="font-family:'Source Sans 3',sans-serif; font-size:9px; font-weight:600;
            letter-spacing:5px; text-transform:uppercase; color:rgba(255,255,255,0.6); margin:0 0 12px 0;
            position:relative;">
            Members
        </p>
        <div style="display:flex; flex-wrap:wrap; gap:10px; margin-bottom:24px;">
            <span style="font-family:'Source Sans 3',sans-serif; font-size:13px; color:#fff;
                background:rgba(255,255,255,0.12); border:1px solid rgba(255,255,255,0.22);
                border-radius:30px; padding:5px 16px;">Lebogang</span>
            <span style="font-family:'Source Sans 3',sans-serif; font-size:13px; color:#fff;
                background:rgba(255,255,255,0.12); border:1px solid rgba(255,255,255,0.22);
                border-radius:30px; padding:5px 16px;">Sibongile</span>
            <span style="font-family:'Source Sans 3',sans-serif; font-size:13px; color:#fff;
                background:rgba(255,255,255,0.12); border:1px solid rgba(255,255,255,0.22);
                border-radius:30px; padding:5px 16px;">Tersh</span>
            <span style="font-family:'Source Sans 3',sans-serif; font-size:13px; color:#fff;
                background:rgba(255,255,255,0.12); border:1px solid rgba(255,255,255,0.22);
                border-radius:30px; padding:5px 16px;">Tshepang</span>
            <span style="font-family:'Source Sans 3',sans-serif; font-size:13px; color:#fff;
                background:rgba(255,255,255,0.12); border:1px solid rgba(255,255,255,0.22);
                border-radius:30px; padding:5px 16px;">Lethukuthula</span>
        </div>

        <!-- Divider -->
        <div style="height:1px; background:linear-gradient(90deg, rgba(255,255,255,0.2), rgba(255,255,255,0.05));
            margin-bottom:24px;"></div>

        <!-- Meta Row -->
        <div style="display:flex; gap:0; flex-wrap:wrap; position:relative;">

            <div style="flex:1; min-width:140px; padding-right:24px; position:relative;">
                <p style="font-family:'Source Sans 3',sans-serif; font-size:9px; font-weight:600;
                    letter-spacing:4px; text-transform:uppercase; color:rgba(255,255,255,0.6); margin:0 0 6px 0;">
                    Dataset</p>
                <p style="font-family:'Source Sans 3',sans-serif; font-size:13px; color:#fff; margin:0;">
                    Week-3-Employee-Data.csv</p>
                <div style="position:absolute; right:0; top:0; bottom:0; width:1px;
                    background:linear-gradient(180deg, transparent, rgba(255,255,255,0.2), transparent);"></div>
            </div>

            <div style="flex:1; min-width:140px; padding:0 24px; position:relative;">
                <p style="font-family:'Source Sans 3',sans-serif; font-size:9px; font-weight:600;
                    letter-spacing:4px; text-transform:uppercase; color:rgba(255,255,255,0.6); margin:0 0 6px 0;">
                    Tools</p>
                <div style="display:flex; flex-wrap:wrap; gap:5px;">
                    <span style="font-family:'Source Sans 3',sans-serif; font-size:11px;
                        color:rgba(255,255,255,0.85); background:rgba(255,255,255,0.12);
                        border-radius:4px; padding:2px 8px;">Python</span>
                    <span style="font-family:'Source Sans 3',sans-serif; font-size:11px;
                        color:rgba(255,255,255,0.85); background:rgba(255,255,255,0.12);
                        border-radius:4px; padding:2px 8px;">pandas</span>
                    <span style="font-family:'Source Sans 3',sans-serif; font-size:11px;
                        color:rgba(255,255,255,0.85); background:rgba(255,255,255,0.12);
                        border-radius:4px; padding:2px 8px;">Jupyter</span>
                </div>
                <div style="position:absolute; right:0; top:0; bottom:0; width:1px;
                    background:linear-gradient(180deg, transparent, rgba(255,255,255,0.2), transparent);"></div>
            </div>

            <div style="flex:1; min-width:140px; padding-left:24px;">
                <p style="font-family:'Source Sans 3',sans-serif; font-size:9px; font-weight:600;
                    letter-spacing:4px; text-transform:uppercase; color:rgba(255,255,255,0.6); margin:0 0 6px 0;">
                    Date</p>
                <p style="font-family:'Source Sans 3',sans-serif; font-size:13px; color:#fff; margin:0;">
                    February 2026</p>
            </div>

        </div>
    </div>

    <!-- Bottom accent bar -->
    <div style="position:absolute; bottom:0; left:0; right:0; height:3px;
        background: linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);
    "></div>

</div>
"""))

<div style="
background: linear-gradient(145deg, #f5eeff 0%, #e8d6f7 40%, #d4b8ee 70%, #ede0fa 100%);
border-radius:24px; padding:56px 48px 48px; position:relative; overflow:hidden;
box-shadow:0 30px 80px rgba(74,31,138,0.25), 0 8px 24px rgba(0,0,0,0.15);
max-width:780px; margin:auto; font-family:'Source Sans 3',sans-serif;">
<div style="position:absolute; top:0; right:0; bottom:0; left:0; background:radial-gradient(ellipse 60% 50% at 90% 10%, rgba(255,255,255,0.55) 0%, transparent 60%), radial-gradient(ellipse 40% 40% at 5% 90%, rgba(190,159,225,0.3) 0%, transparent 60%); pointer-events:none;"></div>
<div style="position:absolute; width:180px; height:180px; top:-60px; right:-50px; border-radius:50%; background:radial-gradient(circle, rgba(107,47,175,0.12) 0%, transparent 70%); border:1px solid rgba(107,47,175,0.08); pointer-events:none;"></div>
<div style="position:absolute; width:80px; height:80px; top:50%; left:-20px; border-radius:50%; background:radial-gradient(circle, rgba(107,47,175,0.08) 0%, transparent 70%); pointer-events:none;"></div>
<div style="position:absolute; top:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
<div style="text-align:center; margin-bottom:36px; position:relative;">
<p style="font-family:'Source Sans 3',sans-serif; font-size:10px; font-weight:600; letter-spacing:7px; text-transform:uppercase; color:#7b4db5; margin:0 0 18px 0; text-align:center;">Navigation</p>
<h1 style="font-family:'Playfair Display',serif; font-size:38px; font-weight:400; color:#2a0f5e; letter-spacing:3px; line-height:1.1; margin:0 0 10px 0; text-align:center;">Table of Contents</h1>
<p style="font-family:'Source Sans 3',sans-serif; font-size:11px; letter-spacing:6px; text-transform:uppercase; color:#9b70cc; margin:0; text-align:center;">Complete roadmap of all cleaning and preparation phases</p>
<div style="width:60px; height:1px; background:linear-gradient(90deg, transparent, rgba(107,47,175,0.4), transparent); margin:24px auto;"></div>
</div>
<div style="background:radial-gradient(ellipse at 15% 10%, rgba(180,150,230,0.14) 0%, transparent 50%), radial-gradient(ellipse at 85% 90%, rgba(90,50,150,0.10) 0%, transparent 50%), radial-gradient(ellipse at 50% 50%, rgba(140,100,210,0.06) 0%, transparent 60%), linear-gradient(150deg, #6b3fa0 0%, #7344a8 10%, #7b4db5 25%, #8254bc 38%, #8a5ac2 50%, #8254bc 62%, #7b4db5 75%, #7344a8 90%, #7040aa 100%); border-radius:16px; padding:36px 40px; border:1px solid rgba(255,255,255,0.18); box-shadow:0 30px 70px rgba(74,31,138,0.40), 0 12px 28px rgba(0,0,0,0.20), 0 4px 10px rgba(74,31,138,0.15), inset 0 1px 0 rgba(255,255,255,0.18), inset 0 -1px 0 rgba(0,0,0,0.12); position:relative; overflow:hidden;">
<div style="position:absolute; top:-30px; right:-30px; width:200px; height:200px; background:radial-gradient(circle, rgba(200,175,240,0.12) 0%, transparent 70%); border-radius:50%; pointer-events:none;"></div>
<div style="position:absolute; bottom:-25px; left:-25px; width:170px; height:170px; background:radial-gradient(circle, rgba(90,50,150,0.08) 0%, transparent 70%); border-radius:50%; pointer-events:none;"></div>
<div style="position:absolute; top:0; left:20px; right:20px; height:1px; background:linear-gradient(90deg, transparent, rgba(255,255,255,0.20) 25%, rgba(255,255,255,0.38) 50%, rgba(255,255,255,0.20) 75%, transparent);"></div>
<table style="width:100%; border-collapse:collapse; position:relative; background:transparent !important;">
<thead style="background:transparent !important;">
<tr style="background:transparent !important;">
<th style="font-family:'Source Sans 3',sans-serif; font-size:9px; font-weight:600; letter-spacing:5px; text-transform:uppercase; color:#2a0f5e !important; text-align:left; padding:0 0 14px 0; border-bottom:1px solid rgba(107,47,175,0.2); background:transparent !important;">Phase</th>
<th style="font-family:'Source Sans 3',sans-serif; font-size:9px; font-weight:600; letter-spacing:5px; text-transform:uppercase; color:#2a0f5e !important; text-align:left; padding:0 0 14px 0; border-bottom:1px solid rgba(107,47,175,0.2); background:transparent !important;">Section</th>
<th style="font-family:'Source Sans 3',sans-serif; font-size:9px; font-weight:600; letter-spacing:5px; text-transform:uppercase; color:#2a0f5e !important; text-align:left; padding:0 0 14px 0; border-bottom:1px solid rgba(107,47,175,0.2); background:transparent !important;">Cells</th>
</tr>
</thead>
<tbody style="background:transparent !important;">
<tr style="background:transparent !important;">
<td style="font-family:'Source Sans 3',sans-serif; font-size:13px; font-weight:600; color:#2a0f5e !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;"><span style="background:rgba(107,47,175,0.15); border:1px solid rgba(107,47,175,0.25); border-radius:4px; padding:2px 10px; font-size:11px; color:#3b1278 !important;">01</span></td>
<td style="font-family:'Source Sans 3',sans-serif; font-size:14px; font-weight:500; color:#2a0f5e !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;">Setup</td>
<td style="font-family:'Source Sans 3',sans-serif; font-size:12px; color:#3b1278 !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;">2 -- 4</td>
</tr>
<tr style="background:transparent !important;">
<td style="font-family:'Source Sans 3',sans-serif; font-size:13px; font-weight:600; color:#2a0f5e !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;"><span style="background:rgba(107,47,175,0.15); border:1px solid rgba(107,47,175,0.25); border-radius:4px; padding:2px 10px; font-size:11px; color:#3b1278 !important;">02</span></td>
<td style="font-family:'Source Sans 3',sans-serif; font-size:14px; font-weight:500; color:#2a0f5e !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;">Data Inspection</td>
<td style="font-family:'Source Sans 3',sans-serif; font-size:12px; color:#3b1278 !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;">5 -- 16</td>
</tr>
<tr style="background:transparent !important;">
<td style="font-family:'Source Sans 3',sans-serif; font-size:13px; font-weight:600; color:#2a0f5e !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;"><span style="background:rgba(107,47,175,0.15); border:1px solid rgba(107,47,175,0.25); border-radius:4px; padding:2px 10px; font-size:11px; color:#3b1278 !important;">03</span></td>
<td style="font-family:'Source Sans 3',sans-serif; font-size:14px; font-weight:500; color:#2a0f5e !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;">Fix Data Types</td>
<td style="font-family:'Source Sans 3',sans-serif; font-size:12px; color:#3b1278 !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;">17 -- 22</td>
</tr>
<tr style="background:transparent !important;">
<td style="font-family:'Source Sans 3',sans-serif; font-size:13px; font-weight:600; color:#2a0f5e !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;"><span style="background:rgba(107,47,175,0.15); border:1px solid rgba(107,47,175,0.25); border-radius:4px; padding:2px 10px; font-size:11px; color:#3b1278 !important;">04</span></td>
<td style="font-family:'Source Sans 3',sans-serif; font-size:14px; font-weight:500; color:#2a0f5e !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;">String Cleaning</td>
<td style="font-family:'Source Sans 3',sans-serif; font-size:12px; color:#3b1278 !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;">23 -- 37</td>
</tr>
<tr style="background:transparent !important;">
<td style="font-family:'Source Sans 3',sans-serif; font-size:13px; font-weight:600; color:#2a0f5e !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;"><span style="background:rgba(107,47,175,0.15); border:1px solid rgba(107,47,175,0.25); border-radius:4px; padding:2px 10px; font-size:11px; color:#3b1278 !important;">05</span></td>
<td style="font-family:'Source Sans 3',sans-serif; font-size:14px; font-weight:500; color:#2a0f5e !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;">Missing Values</td>
<td style="font-family:'Source Sans 3',sans-serif; font-size:12px; color:#3b1278 !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;">38 -- 45</td>
</tr>
<tr style="background:transparent !important;">
<td style="font-family:'Source Sans 3',sans-serif; font-size:13px; font-weight:600; color:#2a0f5e !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;"><span style="background:rgba(107,47,175,0.15); border:1px solid rgba(107,47,175,0.25); border-radius:4px; padding:2px 10px; font-size:11px; color:#3b1278 !important;">06</span></td>
<td style="font-family:'Source Sans 3',sans-serif; font-size:14px; font-weight:500; color:#2a0f5e !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;">Deduplication</td>
<td style="font-family:'Source Sans 3',sans-serif; font-size:12px; color:#3b1278 !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;">46 -- 47</td>
</tr>
<tr style="background:transparent !important;">
<td style="font-family:'Source Sans 3',sans-serif; font-size:13px; font-weight:600; color:#2a0f5e !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;"><span style="background:rgba(107,47,175,0.15); border:1px solid rgba(107,47,175,0.25); border-radius:4px; padding:2px 10px; font-size:11px; color:#3b1278 !important;">07</span></td>
<td style="font-family:'Source Sans 3',sans-serif; font-size:14px; font-weight:500; color:#2a0f5e !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;">Data Validation</td>
<td style="font-family:'Source Sans 3',sans-serif; font-size:12px; color:#3b1278 !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;">48 -- 52</td>
</tr>
<tr style="background:transparent !important;">
<td style="font-family:'Source Sans 3',sans-serif; font-size:13px; font-weight:600; color:#2a0f5e !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;"><span style="background:rgba(107,47,175,0.15); border:1px solid rgba(107,47,175,0.25); border-radius:4px; padding:2px 10px; font-size:11px; color:#3b1278 !important;">08</span></td>
<td style="font-family:'Source Sans 3',sans-serif; font-size:14px; font-weight:500; color:#2a0f5e !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;">Final Review</td>
<td style="font-family:'Source Sans 3',sans-serif; font-size:12px; color:#3b1278 !important; padding:14px 0; border-bottom:1px solid rgba(107,47,175,0.1); background:transparent !important;">53 -- 56</td>
</tr>
<tr style="background:transparent !important;">
<td style="font-family:'Source Sans 3',sans-serif; font-size:13px; font-weight:600; color:#2a0f5e !important; padding:14px 0 0 0; background:transparent !important;"><span style="background:rgba(107,47,175,0.15); border:1px solid rgba(107,47,175,0.25); border-radius:4px; padding:2px 10px; font-size:11px; color:#3b1278 !important;">09</span></td>
<td style="font-family:'Source Sans 3',sans-serif; font-size:14px; font-weight:500; color:#2a0f5e !important; padding:14px 0 0 0; background:transparent !important;">HR KPIs</td>
<td style="font-family:'Source Sans 3',sans-serif; font-size:12px; color:#3b1278 !important; padding:14px 0 0 0; background:transparent !important;">57 -- 64</td>
</tr>
</tbody>
</table>
</div>
<div style="position:absolute; bottom:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
</div>

<div style="
background: linear-gradient(145deg, #f5eeff 0%, #e8d6f7 40%, #d4b8ee 70%, #ede0fa 100%);
border-radius:24px; padding:48px 48px 42px; position:relative; overflow:hidden;
box-shadow:0 30px 80px rgba(74,31,138,0.25), 0 8px 24px rgba(0,0,0,0.15);
max-width:780px; margin:auto; font-family:'Source Sans 3',sans-serif;">
<div style="position:absolute; top:0; right:0; bottom:0; left:0; background:radial-gradient(ellipse 60% 50% at 90% 10%, rgba(255,255,255,0.55) 0%, transparent 60%), radial-gradient(ellipse 40% 40% at 5% 90%, rgba(190,159,225,0.3) 0%, transparent 60%); pointer-events:none;"></div>
<div style="position:absolute; top:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
<p style="font-family:'Source Sans 3',sans-serif; font-size:10px; font-weight:600; letter-spacing:7px; text-transform:uppercase; color:#7b4db5; margin:0 0 10px 0; position:relative;">Phase 1</p>
<h2 style="font-family:'Playfair Display',serif; font-size:36px; font-weight:400; color:#2a0f5e; letter-spacing:2px; line-height:1.2; margin:0 0 10px 0; position:relative;">Setup</h2>
<p style="font-family:'Source Sans 3',sans-serif; font-size:13px; font-weight:400; color:#9b70cc; letter-spacing:0.5px; margin:0 0 20px 0; position:relative;">Importing required libraries and loading the raw employee dataset into the working environment.</p>
<div style="height:1px; position:relative; background:linear-gradient(90deg, rgba(107,47,175,0.3), rgba(107,47,175,0.05));"></div>
<div style="position:absolute; bottom:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
</div>

In [6]:
#  Importing Libraries 

# pandas: the primary data manipulation library.
# It provides the DataFrame structure we use to hold and clean the dataset.
import pandas as pd

# NumPy: numerical computing library.
# and for any numeric operations that pandas delegates to it internally.
import numpy as np

# re: Python's built-in regular expressions module.
# We use it in Phase 7 to validate email address format patterns.
import re

# We use it to calculate employee tenure relative to today's date.
from datetime import datetime

In [7]:
# Loading CSV

# pd.read_csv() reads the raw CSV file from disk into a pandas DataFrame.
# The filename matchs exactly including capitalisation and the .csv extension.
# pandas automatically infers column names from the first row of the file.
df = pd.read_csv('Week-3-Employee-Data.csv')

# Print a confirmation so we know the file loaded without errors.
print(f"Dataset loaded: {df.shape[0]} rows x {df.shape[1]} columns")

Dataset loaded: 155 rows x 17 columns

<div style="
background: linear-gradient(145deg, #f5eeff 0%, #e8d6f7 40%, #d4b8ee 70%, #ede0fa 100%);
border-radius:24px; padding:48px 48px 42px; position:relative; overflow:hidden;
box-shadow:0 30px 80px rgba(74,31,138,0.25), 0 8px 24px rgba(0,0,0,0.15);
max-width:780px; margin:auto; font-family:'Source Sans 3',sans-serif;">
<div style="position:absolute; top:0; right:0; bottom:0; left:0; background:radial-gradient(ellipse 60% 50% at 90% 10%, rgba(255,255,255,0.55) 0%, transparent 60%), radial-gradient(ellipse 40% 40% at 5% 90%, rgba(190,159,225,0.3) 0%, transparent 60%); pointer-events:none;"></div>
<div style="position:absolute; top:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
<p style="font-family:'Source Sans 3',sans-serif; font-size:10px; font-weight:600; letter-spacing:7px; text-transform:uppercase; color:#7b4db5; margin:0 0 10px 0; position:relative;">Phase 2</p>
<h2 style="font-family:'Playfair Display',serif; font-size:36px; font-weight:400; color:#2a0f5e; letter-spacing:2px; line-height:1.2; margin:0 0 10px 0; position:relative;">Data Inspection</h2>
<p style="font-family:'Source Sans 3',sans-serif; font-size:13px; font-weight:400; color:#9b70cc; letter-spacing:0.5px; margin:0 0 20px 0; position:relative;">Before making any changes, we examine the structure, data types, missing values, duplicates, and full range of values across every column — establishing a documented baseline for all cleaning decisions that follow.</p>
<div style="height:1px; position:relative; background:linear-gradient(90deg, rgba(107,47,175,0.3), rgba(107,47,175,0.05));"></div>
<div style="position:absolute; bottom:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
</div>

In [8]:
# Previewing First 10 Rows
df.head(10)

,employee_id,first_name,last_name,email,gender,department,job_title,hire_date,exit_date,is_active,salary,currency,country,state,city,manager_id,performance_score
0,1001,Ken,Naidoo,ken.naidoo@example.com,Male,HR,Sales Rep,29/05/2017,NaN,True,"55,286.31",GBP,south-africa,Western Cape,NaN,NaN,NaN
1,1002,Sam,Smith,sam.smith@mail.com,M,H.R.,Sales Rep,04-27-2016,NaN,True,29408.75,GBP,south-africa,NaN,Johannesburg,1001.0,C
2,1003,Oscar,Mthembu,oscar.mthembu@mail.com,Male,Ops,Engineer,12-02-2015,NaN,False,"35,393.84",$,SA,KZN,Cape Town,NaN,NaN
3,1004,Sam,Brown,sam.brown@example,M,Sales,Senior Analyst,01-19-2016,NaN,True,39890.2,£,USA,KZN,NaN,1003.0,C
4,1005,Faith,Mthembu,faith.mthembu@mail.com,M,H.R.,Engineer,06-18-2019,2022/01/22,NaN,25532.92,GBP,United Kingdom,NaN,Polokwane,NaN,B
5,1006,Esi,Dlamini,esi.dlaminimail.com,M,IT,Manager,2017-12-12,NaN,False,35024.79,GBP,South Africa,Limpopo,NaN,1005.0,D
6,1007,David,Zuma,david.zuma@example.com,M,Sales,Manager,2016-03-26,2017/02/28,NaN,"34,989.32",R,U.K.,Western Cape,NaN,1003.0,A
7,1008,David,Nguyen,david.nguyen@example,Other,H.R.,Senior Analyst,11-04-2018,NaN,True,13943.31,£,United States,Gauteng,NaN,1006.0,NaN
8,1009,Liam,Naidoo,liam.naidoo@mail.com,Other,Operations,Engineer,09-07-2017,2020/09/01,NaN,47211.9,$,United Kingdom,Western Cape,NaN,1006.0,C
9,1010,Chipo,Nkosi,chipo.nkosi@mail.com,M,Sales,Analyst,05-17-2020,NaN,True,42205.98,$,SA,Limpopo,NaN,1002.0,D

In [9]:
# genereates descriptive statistics Categorical / String Column Statistics
df.describe(include='object')

,first_name,last_name,email,gender,department,job_title,hire_date,exit_date,is_active,salary,currency,country,state,city,performance_score
count,155,155,155,155,155,155,155,49,106,155,155,155,102,106,131
unique,81,28,146,5,13,9,148,47,2,150,6,9,4,5,4
top,Faith,Nguyen,faith.govender@company.co.za,M,H.R.,Data Scientist,07/09/2017,2017/02/28,True,41063.59,ZAR,U.K.,KZN,Cape Town,D
freq,5,9,2,37,19,21,2,2,53,2,36,25,31,29,39

In [10]:
# Creates and prints a summary report of missing values (count, percentage, and data type) for each DataFrame column
missing_count = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)

missing_report = pd.DataFrame({
    'Missing Count': missing_count,
    'Missing %': missing_pct,
    'Type': df.dtypes
})

print(missing_report)

                   Missing Count  Missing %     Type
employee_id                    0       0.00    int64
first_name                     0       0.00   object
last_name                      0       0.00   object
email                          0       0.00   object
gender                         0       0.00   object
department                     0       0.00   object
job_title                      0       0.00   object
hire_date                      0       0.00   object
exit_date                    106      68.39   object
is_active                     49      31.61   object
salary                         0       0.00   object
currency                       0       0.00   object
country                        0       0.00   object
state                         53      34.19   object
city                          49      31.61   object
manager_id                    27      17.42  float64
performance_score             24      15.48   object

In [11]:
# Identifies and displays rows containing at least one missing value 
# this is to assess the scope and patterns of incomplete data before cleaning
rows_with_missing = df[df.isnull().any(axis=1)]

print(f"Rows with missing data: {len(rows_with_missing)} / {len(df)}")

rows_with_missing

Rows with missing data: 155 / 155

,employee_id,first_name,last_name,email,gender,department,job_title,hire_date,exit_date,is_active,salary,currency,country,state,city,manager_id,performance_score
0,1001,Ken,Naidoo,ken.naidoo@example.com,Male,HR,Sales Rep,29/05/2017,NaN,True,"55,286.31",GBP,south-africa,Western Cape,NaN,NaN,NaN
1,1002,Sam,Smith,sam.smith@mail.com,M,H.R.,Sales Rep,04-27-2016,NaN,True,29408.75,GBP,south-africa,NaN,Johannesburg,1001.0,C
2,1003,Oscar,Mthembu,oscar.mthembu@mail.com,Male,Ops,Engineer,12-02-2015,NaN,False,"35,393.84",$,SA,KZN,Cape Town,NaN,NaN
3,1004,Sam,Brown,sam.brown@example,M,Sales,Senior Analyst,01-19-2016,NaN,True,39890.2,£,USA,KZN,NaN,1003.0,C
4,1005,Faith,Mthembu,faith.mthembu@mail.com,M,H.R.,Engineer,06-18-2019,2022/01/22,NaN,25532.92,GBP,United Kingdom,NaN,Polokwane,NaN,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,1007,David,Zuma,david.zuma@example.com,M,Sales,Manager,2016-03-26,2017/02/28,NaN,"34,989.32",R,U.K.,Western Cape,NaN,1003.0,A
151,1004,Sam,Brown,sam.brown@example,M,Sales,Senior Analyst,01-19-2016,NaN,True,39890.2,£,USA,KZN,NaN,1003.0,C
152,1114,Faith,Govender,faith.govender@company.co.za,Male,Engineering,Data Scientist,07/09/2017,2022/04/08,NaN,41790.59,R,USA,Limpopo,Polokwane,1039.0,B
153,1013,Que,Khan,que.khan@example.com,F,H.R.,Manager,08-02-2016,NaN,False,41063.59,ZAR,United States,Gauteng,Cape Town,1001.0,D
154,1025,Abel,Khan,abel.khan@mail.com,M,Finance,Senior Analyst,09/07/2021,NaN,False,34455.37,GBP,United Kingdom,Gauteng,NaN,1016.0,D

In [12]:
# Checks for fully duplicated rows and repeated employee_id values 
# to detect data entry errors or unintended record duplication
print(f"Exact duplicates: {df.duplicated().sum()}")

print(f"Duplicate employee_ids: {df.duplicated(subset='employee_id').sum()}")

Exact duplicates: 5
Duplicate employee_ids: 5

In [13]:
# Extracts and displays all rows with duplicated employee_id values 
# (including originals) to review conflicting or repeated records

#creating varibale
dupes = df[df.duplicated(subset='employee_id', keep=False)].sort_values('employee_id')

print(f"Duplication records: {len(dupes)}")

if len(dupes) > 0:
    dupes

Duplication records: 10

In [14]:
# Loop through all columns with string (object) data type
for col in df.select_dtypes(include='object').columns:

    # Get the unique values present in the current column
    vals = df[col].unique()

    # Print a formatted header showing the column name and number of unique values
    print(f"\n{'='*60}\nCOLUMN: {col} ({len(vals)} unique)\n{'='*60}")

    # Iterate over the unique values in sorted order (safe even if NaN exists)
    for val in sorted(vals, key=str):

        # Print each value and the number of rows in which it appears
        print(f"  '{val}' — {df[df[col] == val].shape[0]}")

============================================================
COLUMN: first_name (81 unique)
============================================================
  ' Abel' — 1
  ' Abel ' — 4
  ' Alice' — 2
  ' Bea' — 1
  ' Bea ' — 1
  ' Bob' — 3
  ' Bob ' — 3
  ' Chad' — 1
  ' Chipo' — 3
  ' Chipo ' — 1
  ' David' — 3
  ' David ' — 2
  ' Esi ' — 1
  ' Faith' — 1
  ' Faith ' — 5
  ' Grace' — 1
  ' Grace ' — 1
  ' Henry ' — 2
  ' Isaac' — 2
  ' Isaac ' — 2
  ' Ken' — 4
  ' Ken ' — 2
  ' Liam' — 3
  ' Nia' — 2
  ' Nia ' — 1
  ' Oscar ' — 2
  ' Que' — 2
  ' Rae ' — 1
  ' Sam ' — 2
  ' Tari' — 2
  ' Una' — 3
  ' Una ' — 3
  ' Vin ' — 3
  ' Yara ' — 1
  ' Zed ' — 2
  'Abel' — 1
  'Abel ' — 1
  'Alice' — 3
  'Alice ' — 3
  'Bea' — 1
  'Bea ' — 1
  'Bob ' — 1
  'Chad ' — 2
  'Chipo' — 2
  'Chipo ' — 1
  'David' — 2
  'David ' — 3
  'Esi' — 3
  'Esi ' — 1
  'Faith' — 3
  'Faith ' — 1
  'Grace' — 2
  'Henry' — 3
  'Isaac' — 1
  'Isaac ' — 2
  'Jane' — 2
  'Jane ' — 2
  'Liam' — 1
  'Liam ' — 2
  'Mai' — 2
  'Mai ' — 1
  'Nia' — 2
  'Oscar' — 1
  'Oscar ' — 1
  'Pat' — 1
  'Pat ' — 2
  'Que' — 2
  'Que ' — 3
  'Rae' — 2
  'Rae ' — 1
  'Sam' — 3
  'Sam ' — 1
  'Tari ' — 2
  'Una' — 1
  'Una ' — 1
  'Vin ' — 3
  'Will' — 2
  'Yara' — 1
  'Yara ' — 3
  'Zed' — 1
  'Zed ' — 2

============================================================
COLUMN: last_name (28 unique)
============================================================
  'Brown' — 4
  'Brown ' — 8
  'Dlamini' — 6
  'Dlamini ' — 3
  'Govender' — 7
  'Govender ' — 4
  'Khan' — 6
  'Khan ' — 6
  'Moyo' — 1
  'Moyo ' — 6
  'Mthembu' — 4
  'Mthembu ' — 5
  'Naidoo' — 7
  'Naidoo ' — 8
  'Ndlovu' — 4
  'Ndlovu ' — 6
  'Nguyen' — 8
  'Nguyen ' — 9
  'Nkosi' — 8
  'Nkosi ' — 5
  'Pillay' — 5
  'Pillay ' — 5
  'Smith' — 4
  'Smith ' — 5
  'Zuma' — 9
  'Zuma ' — 4
  'van Wyk' — 3
  'van Wyk ' — 5

============================================================
COLUMN: email (146 unique)
============================================================
  'abel.khan@mail.com' — 2
  'abel.moyo@mail.com' — 1
  'abel.ndlovu@company.co.za' — 2
  'abel.nguyen@company.co.za' — 1
  'abel.zuma@company.co.za' — 1
  'alice.brownexample.com' — 1
  'alice.govender@company.co.za' — 1
  'alice.moyo@company.co.za' — 1
  'alice.naidoo@company.co.za' — 1
  'alice.naidoo@example' — 1
  'alice.ndlovumail.com' — 1
  'alice.nguyen@example.com' — 1
  'alice.smith@example.com' — 1
  'bea.khan@example.com' — 1
  'bea.mthembu@example' — 1
  'bea.naidoo@mail.com' — 1
  'bea.smith@example' — 1
  'bob.brown@example.com' — 1
  'bob.dlamini@example' — 1
  'bob.mthembu@example.com' — 1
  'bob.naidoo@example' — 1
  'bob.ndlovu@mail.com' — 1
  'bob.nguyen@mail.com' — 1
  'bob.pillay@example' — 1
  'chad.govender@company.co.za' — 1
  'chad.nguyen@example' — 1
  'chad.van wyk@example.com' — 1
  'chipo.nguyen@company.co.za' — 2
  'chipo.nkosi@company.co.za' — 1
  'chipo.nkosi@mail.com' — 1
  'chipo.pillay@mail.com' — 1
  'chipo.van wyk@company.co.za' — 1
  'chipo.van wyk@example.com' — 1
  'david.brown@example.com' — 1
  'david.govender@company.co.za' — 1
  'david.khan@example' — 1
  'david.nguyen@example' — 2
  'david.nkosiexample.com' — 1
  'david.zuma@company.co.za' — 1
  'david.zuma@example' — 1
  'david.zuma@example.com' — 2
  'esi.dlaminimail.com' — 1
  'esi.khancompany.co.za' — 1
  'esi.moyo@mail.com' — 1
  'esi.moyocompany.co.za' — 1
  'esi.van wyk@example.com' — 1
  'faith.govender@company.co.za' — 2
  'faith.khan@mail.com' — 1
  'faith.mthembu@mail.com' — 1
  'faith.naidoo@example.com' — 1
  'faith.ndlovu@example.com' — 1
  'faith.nkosi@example.com' — 1
  'faith.pillay@company.co.za' — 1
  'faith.pillay@example' — 1
  'faith.zuma@mail.com' — 1
  'grace.naidoo@example.com' — 1
  'grace.nguyen@example.com' — 1
  'grace.nkosi@example' — 1
  'grace.nkosiexample.com' — 1
  'henry.brown@mail.com' — 1
  'henry.dlamini@company.co.za' — 1
  'henry.nkosicompany.co.za' — 1
  'henry.zuma@company.co.za' — 1
  'henry.zuma@mail.com' — 1
  'isaac.govender@mail.com' — 1
  'isaac.mthembu@example' — 1
  'isaac.mthembu@example.com' — 2
  'isaac.nguyen@example.com' — 1
  'isaac.nkosiexample' — 1
  'isaac.pillay@mail.com' — 1
  'jane.nkosi@company.co.za' — 1
  'jane.nkosi@example' — 1
  'jane.pillay@example' — 1
  'jane.van wyk@example.com' — 1
  'ken.govender@company.co.za' — 1
  'ken.govender@mail.com' — 1
  'ken.khan@example' — 1
  'ken.naidoo@example.com' — 1
  'ken.ndlovu@mail.com' — 1
  'ken.pillay@example.com' — 1
  'liam.brown@mail.com' — 1
  'liam.dlamini@example.com' — 1
  'liam.naidoo@example' — 1
  'liam.naidoo@mail.com' — 1
  'liam.nkosi@mail.com' — 1
  'liam.smithexample.com' — 1
  'mai.khan@example.com' — 1
  'mai.naidooexample.com' — 1
  'mai.van wykmail.com' — 1
  'nia.khan@example' — 1
  'nia.nguyen@company.co.za' — 1
  'nia.pillay@example' — 1
  'nia.smith@mail.com' — 1
  'nia.van wyk@example.com' — 1
  'oscar.dlamini@example' — 1
  'oscar.mthembu@company.co.za' — 1
  'oscar.mthembu@mail.com' — 1
  'oscar.smith@company.co.za' — 1
  'pat.brown@example.com' — 1
  'pat.van wyk@company.co.za' — 1
  'pat.zuma@example' — 1
  'que.brown@example.com' — 1
  'que.khan@example.com' — 2
  'que.mthembu@company.co.za' — 1
  'que.pillay@company.co.za' — 1
  'que.zuma@example' — 1
  'que.zuma@example.com' — 1
  'rae.brown@example.com' — 1
  'rae.moyo@example' — 1
  'rae.moyo@mail.com' — 1
  'rae.nguyen@example.com' — 1
  'sam.brown@example' — 2
  'sam.dlamini@example.com' — 1
  'sam.naidoo@example' — 1
  'sam.naidoo@mail.com' — 1
  'sam.smith@mail.com' — 1
  'tari.brown@example.com' — 1
  'tari.dlamini@example' — 1
  'tari.naidoo@example.com' — 1
  'tari.nguyen@example.com' — 1
  'una.dlamini@mail.com' — 1
  'una.govender@company.co.za' — 1
  'una.naidoo@company.co.za' — 1
  'una.ndlovu@company.co.za' — 1
  'una.nguyen@company.co.za' — 1
  'una.nkosi@mail.com' — 1
  'una.smith@example.com' — 1
  'una.zuma@company.co.za' — 1
  'vin.dlamini@mail.com' — 1
  'vin.govender@mail.com' — 1
  'vin.ndlovu@example.com' — 1
  'vin.nguyencompany.co.za' — 1
  'vin.pillay@mail.com' — 1
  'vin.smith@example' — 1
  'will.nkosi@example' — 1
  'will.smith@mail.com' — 1
  'yara.govender@example.com' — 1
  'yara.khan@example' — 1
  'yara.moyo@example.com' — 1
  'yara.nguyenexample.com' — 1
  'yara.zuma@example' — 1
  'zed.brown@example.com' — 1
  'zed.naidoo@example.com' — 1
  'zed.ndlovu@company.co.za' — 1
  'zed.ndlovuexample.com' — 1
  'zed.nguyen@example' — 1

============================================================
COLUMN: gender (5 unique)
============================================================
  'F' — 29
  'Female' — 30
  'M' — 37
  'Male' — 34
  'Other' — 25

============================================================
COLUMN: department (13 unique)
============================================================
  'Eng' — 12
  'Engineering' — 16
  'FIN' — 6
  'Finance' — 13
  'H.R.' — 19
  'HR' — 12
  'Human Resources' — 9
  'IT' — 14
  'Information Technology' — 15
  'Operations' — 7
  'Ops' — 10
  'Sales' — 12
  'sales' — 10

============================================================
COLUMN: job_title (9 unique)
============================================================
  'Accountant' — 15
  'Analyst' — 16
  'Clerk' — 20
  'Data Scientist' — 21
  'Engineer' — 16
  'HR Officer' — 12
  'Manager' — 20
  'Sales Rep' — 15
  'Senior Analyst' — 20

============================================================
COLUMN: hire_date (148 unique)
============================================================
  '01-03-2020' — 1
  '01-05-2017' — 1
  '01-07-2017' — 1
  '01-09-2018' — 1
  '01-10-2021' — 1
  '01-19-2016' — 2
  '01-19-2022' — 1
  '01-26-2018' — 1
  '01-30-2022' — 1
  '02-16-2015' — 1
  '02/01/2017' — 1
  '02/04/2015' — 1
  '02/04/2021' — 1
  '02/06/2019' — 1
  '03-14-2019' — 1
  '03-16-2017' — 1
  '03-17-2016' — 1
  '03-20-2021' — 1
  '03-24-2017' — 1
  '03-26-2015' — 1
  '03/01/2020' — 1
  '04-04-2017' — 1
  '04-08-2016' — 1
  '04-11-2019' — 1
  '04-14-2015' — 1
  '04-17-2022' — 1
  '04-19-2021' — 1
  '04-27-2016' — 1
  '04-30-2020' — 1
  '04/01/2015' — 1
  '04/03/2017' — 1
  '05-01-2018' — 1
  '05-03-2019' — 1
  '05-07-2018' — 1
  '05-17-2020' — 2
  '05-19-2016' — 1
  '05-23-2022' — 1
  '05-27-2020' — 1
  '05-31-2017' — 1
  '05-31-2019' — 1
  '06-06-2016' — 1
  '06-15-2017' — 1
  '06-15-2020' — 1
  '06-16-2015' — 1
  '06-18-2015' — 1
  '06-18-2019' — 1
  '06-18-2022' — 2
  '06-26-2019' — 1
  '06-29-2022' — 1
  '06/12/2016' — 1
  '07-03-2018' — 1
  '07-05-2015' — 1
  '07-05-2019' — 1
  '07-09-2015' — 1
  '07-17-2019' — 1
  '07-25-2017' — 1
  '07-26-2015' — 1
  '07-28-2022' — 1
  '07-29-2016' — 1
  '07-30-2021' — 1
  '07-31-2015' — 1
  '07/09/2017' — 2
  '08-01-2016' — 1
  '08-01-2017' — 1
  '08-02-2016' — 2
  '08-03-2017' — 1
  '08-05-2016' — 1
  '08-05-2022' — 1
  '08-07-2015' — 1
  '08-11-2015' — 1
  '08-11-2017' — 1
  '08/02/2022' — 1
  '08/04/2018' — 1
  '09-07-2017' — 1
  '09-10-2019' — 1
  '09-10-2020' — 1
  '09-11-2017' — 1
  '09-28-2021' — 1
  '09/07/2021' — 2
  '09/12/2015' — 1
  '09/12/2021' — 1
  '10-05-2017' — 1
  '10-06-2022' — 1
  '10-25-2018' — 1
  '10-28-2021' — 1
  '10/05/2022' — 1
  '11-04-2018' — 1
  '11-05-2018' — 1
  '11-08-2020' — 1
  '11-11-2022' — 1
  '11-13-2018' — 1
  '11-30-2016' — 1
  '11/08/2017' — 1
  '12-01-2016' — 1
  '12-02-2015' — 1
  '12-14-2022' — 1
  '12-16-2018' — 1
  '12-17-2022' — 1
  '12-24-2020' — 1
  '12/07/2017' — 1
  '13/07/2016' — 1
  '15/04/2015' — 1
  '17/01/2022' — 1
  '17/04/2018' — 1
  '17/05/2019' — 1
  '20/02/2018' — 1
  '2015-06-21' — 1
  '2015-08-22' — 1
  '2016-01-16' — 1
  '2016-03-26' — 2
  '2016-06-29' — 1
  '2016-12-16' — 1
  '2017-03-19' — 1
  '2017-04-19' — 1
  '2017-05-29' — 1
  '2017-06-18' — 1
  '2017-08-30' — 1
  '2017-11-06' — 1
  '2017-12-12' — 1
  '2018-01-06' — 1
  '2018-02-02' — 1
  '2018-07-31' — 1
  '2018-10-02' — 1
  '2018-11-09' — 1
  '2018-11-21' — 1
  '2018-11-23' — 1
  '2019-01-02' — 1
  '2019-01-15' — 1
  '2019-01-24' — 1
  '2019-08-07' — 1
  '2019-09-13' — 1
  '2019-10-09' — 1
  '2019-11-17' — 1
  '2020-01-21' — 1
  '2020-03-12' — 1
  '2020-09-29' — 1
  '2021-01-16' — 1
  '2021-05-13' — 1
  '2021-05-27' — 1
  '2021-10-17' — 1
  '2022-01-05' — 1
  '2022-01-28' — 1
  '2022-02-04' — 1
  '2022-02-13' — 1
  '2022-02-22' — 1
  '2022-05-27' — 1
  '2022-12-24' — 1
  '29/05/2017' — 1

============================================================
COLUMN: exit_date (48 unique)
============================================================
  '2015/12/25' — 1
  '2017/02/28' — 2
  '2017/11/25' — 1
  '2018/02/03' — 1
  '2018/06/28' — 1
  '2018/08/25' — 1
  '2019/02/08' — 1
  '2019/04/22' — 1
  '2019/08/01' — 1
  '2019/09/03' — 1
  '2019/09/07' — 1
  '2019/09/22' — 1
  '2020/01/11' — 1
  '2020/03/02' — 1
  '2020/05/07' — 1
  '2020/06/11' — 1
  '2020/08/09' — 1
  '2020/09/01' — 1
  '2020/10/23' — 1
  '2021/01/21' — 1
  '2021/03/28' — 1
  '2021/05/23' — 1
  '2021/06/08' — 1
  '2021/09/05' — 1
  '2021/09/10' — 1
  '2021/12/08' — 1
  '2021/12/31' — 1
  '2022/01/19' — 1
  '2022/01/22' — 1
  '2022/04/08' — 2
  '2022/04/20' — 1
  '2022/05/02' — 1
  '2022/07/28' — 1
  '2022/09/03' — 1
  '2022/10/06' — 1
  '2023/12/30' — 1
  '2024/03/11' — 1
  '2024/06/23' — 1
  '2024/09/03' — 1
  '2025/03/04' — 1
  '2025/07/16' — 1
  '2025/09/15' — 1
  '2025/12/28' — 1
  '2026/03/30' — 1
  '2026/07/18' — 1
  '2026/08/08' — 1
  '2026/10/04' — 1
  'nan' — 0

============================================================
COLUMN: is_active (3 unique)
============================================================
  'False' — 53
  'True' — 53
  'nan' — 0

============================================================
COLUMN: salary (150 unique)
============================================================
  '-26089.36' — 1
  '-31403.47' — 1
  '-34329.59' — 1
  '-38232.94' — 1
  '10227.02' — 1
  '11576.26' — 1
  '12123.56' — 1
  '13010.89' — 1
  '13362.82' — 1
  '13663.85' — 1
  '13943.31' — 1
  '14499.93' — 1
  '15187.09' — 1
  '16566.77' — 1
  '16681.71' — 1
  '17,591.86' — 1
  '17561.1' — 1
  '17682.54' — 1
  '17780.44' — 1
  '18961.75' — 1
  '20,197.71' — 1
  '20077.79' — 1
  '20549.36' — 1
  '20676.9' — 1
  '20840.21' — 1
  '21536.45' — 1
  '22,064.18' — 1
  '22399.8' — 1
  '23,917.46' — 1
  '24,626.12' — 1
  '24321.72' — 1
  '24848.93' — 1
  '25118.48' — 1
  '25532.92' — 1
  '25965.95' — 1
  '26467.36' — 1
  '26916.26' — 1
  '27054.09' — 1
  '27222.74' — 1
  '27494.85' — 1
  '27596.94' — 1
  '27910.76' — 1
  '28,820.87' — 1
  '28166.33' — 1
  '28629.75' — 1
  '28704.74' — 1
  '28748.33' — 1
  '29,336.88' — 1
  '29408.75' — 1
  '29502.48' — 1
  '29851.18' — 1
  '30,574.18' — 1
  '30002.31' — 1
  '30137.27' — 1
  '30315.36' — 1
  '30354.32' — 1
  '30398.92' — 1
  '30652.61' — 1
  '30894.6' — 1
  '31,608.38' — 1
  '31,719.41' — 1
  '31047.03' — 1
  '31286.28' — 1
  '31397.68' — 1
  '31544.19' — 1
  '31626.71' — 1
  '31863.72' — 1
  '32,647.67' — 1
  '32,685.73' — 1
  '32087.01' — 1
  '32447.2' — 1
  '32840.16' — 1
  '32941.42' — 1
  '33411.47' — 1
  '33804.67' — 1
  '33862.69' — 1
  '34,989.32' — 2
  '34090.23' — 1
  '34092.04' — 1
  '34455.37' — 2
  '34853.09' — 1
  '35,393.84' — 1
  '35024.79' — 1
  '35266.94' — 1
  '36,303.78' — 1
  '36057.86' — 1
  '360710.4' — 1
  '36217.21' — 1
  '36486.57' — 1
  '36567.48' — 1
  '36852.03' — 1
  '36882.13' — 1
  '37194.81' — 1
  '37516.66' — 1
  '37847.62' — 1
  '38,030.93' — 1
  '380742.08' — 1
  '38293.52' — 1
  '38403.64' — 1
  '38597.7' — 1
  '38983.69' — 1
  '39,698.55' — 1
  '39346.28' — 1
  '39479.97' — 1
  '39492.44' — 1
  '39597.46' — 1
  '39890.2' — 2
  '39986.03' — 1
  '40836.02' — 1
  '40863.5' — 1
  '40953.51' — 1
  '41,654.96' — 1
  '41019.49' — 1
  '41063.59' — 2
  '41425.15' — 1
  '41584.94' — 1
  '416,965.20' — 1
  '41790.59' — 2
  '41816.74' — 1
  '42,856.47' — 1
  '42205.98' — 1
  '42645.35' — 1
  '43,033.02' — 1
  '43,119.55' — 1
  '43820.32' — 1
  '44375.62' — 1
  '45428.47' — 1
  '45732.23' — 1
  '46570.41' — 1
  '47211.9' — 1
  '47671.38' — 1
  '47869.64' — 1
  '49317.03' — 1
  '50562.62' — 1
  '52,543.71' — 1
  '52258.87' — 1
  '52971.67' — 1
  '53039.82' — 1
  '53354.96' — 1
  '54808.4' — 1
  '55,286.31' — 1
  '55394.45' — 1
  '55612.76' — 1
  '55970.93' — 1
  '56193.93' — 1
  '57944.23' — 1
  '59,348.87' — 1
  '61971.14' — 1
  '62119.36' — 1
  '7540.22' — 1

============================================================
COLUMN: currency (6 unique)
============================================================
  '$' — 22
  'GBP' — 25
  'R' — 30
  'USD' — 22
  'ZAR' — 36
  '£' — 20

============================================================
COLUMN: country (9 unique)
============================================================
  'SA' — 15
  'South Africa' — 18
  'U.K.' — 25
  'UK' — 16
  'USA' — 15
  'United Kingdom' — 18
  'United States' — 18
  'ZA' — 17
  'south-africa' — 13

============================================================
COLUMN: state (5 unique)
============================================================
  'Gauteng' — 30
  'KZN' — 31
  'Limpopo' — 17
  'Western Cape' — 24
  'nan' — 0

============================================================
COLUMN: city (6 unique)
============================================================
  'Cape Town' — 29
  'Durban' — 20
  'Johannesburg' — 21
  'Polokwane' — 23
  'Pretoria' — 13
  'nan' — 0

============================================================
COLUMN: performance_score (5 unique)
============================================================
  'A' — 37
  'B' — 25
  'C' — 30
  'D' — 39
  'nan' — 0

<div style="
background: linear-gradient(145deg, #f5eeff 0%, #e8d6f7 40%, #d4b8ee 70%, #ede0fa 100%);
border-radius:24px; padding:48px 48px 42px; position:relative; overflow:hidden;
box-shadow:0 30px 80px rgba(74,31,138,0.25), 0 8px 24px rgba(0,0,0,0.15);
max-width:780px; margin:auto; font-family:'Source Sans 3',sans-serif;">
<div style="position:absolute; top:0; right:0; bottom:0; left:0; background:radial-gradient(ellipse 60% 50% at 90% 10%, rgba(255,255,255,0.55) 0%, transparent 60%), radial-gradient(ellipse 40% 40% at 5% 90%, rgba(190,159,225,0.3) 0%, transparent 60%); pointer-events:none;"></div>
<div style="position:absolute; top:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
<p style="font-family:'Source Sans 3',sans-serif; font-size:10px; font-weight:600; letter-spacing:7px; text-transform:uppercase; color:#7b4db5; margin:0 0 10px 0; position:relative;">Phase 3</p>
<h2 style="font-family:'Playfair Display',serif; font-size:36px; font-weight:400; color:#2a0f5e; letter-spacing:2px; line-height:1.2; margin:0 0 10px 0; position:relative;">Fix Data Types</h2>
<p style="font-family:'Source Sans 3',sans-serif; font-size:13px; font-weight:400; color:#9b70cc; letter-spacing:0.5px; margin:0 0 20px 0; position:relative;">pandas reads every ambiguous column as plain text on import. Here we convert hire_date, exit_date, salary, and manager_id to their correct types so that date arithmetic, numeric aggregation, and relational lookups all behave as expected.</p>
<div style="height:1px; position:relative; background:linear-gradient(90deg, rgba(107,47,175,0.3), rgba(107,47,175,0.05));"></div>
<div style="position:absolute; bottom:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
</div>

In [15]:
# Print the column type and first few raw values before conversion
print("BEFORE:")
print(f"  Type: {df['hire_date'].dtype}")
for i in range(min(5, len(df))):
    # Show sample values for auditing purposes
    print(f"    Row {i}: '{df['hire_date'].iloc[i]}'")

# Convert the 'hire_date' column to datetime, handling mixed formats and coercing errors
df['hire_date'] = pd.to_datetime(df['hire_date'], format='mixed', dayfirst=False, errors='coerce')

# Print the updated type, count of unparseable dates, and overall date range
print(f"\nAFTER: {df['hire_date'].dtype} | NaT: {df['hire_date'].isna().sum()} | Range: {df['hire_date'].min()} to {df['hire_date'].max()}")

BEFORE:
  Type: object
    Row 0: '29/05/2017'
    Row 1: '04-27-2016'
    Row 2: '12-02-2015'
    Row 3: '01-19-2016'
    Row 4: '06-18-2019'

AFTER: datetime64[ns] | NaT: 0 | Range: 2015-02-04 00:00:00 to 2022-12-24 00:00:00

In [17]:
# Print the current dtype and number of non-null exit_date values before conversion
print(f"BEFORE: {df['exit_date'].dtype} | Non-null: {df['exit_date'].notna().sum()}")

# Convert 'exit_date' to datetime, handling mixed formats and coercing errors to NaT
df['exit_date'] = pd.to_datetime(df['exit_date'], format='mixed', dayfirst=False, errors='coerce')

# Print the new dtype and count of NaT values after conversion
print(f"AFTER: {df['exit_date'].dtype} | NaT: {df['exit_date'].isna().sum()}")

# If there are any actual exit dates, print the date range for plausibility check
if df['exit_date'].notna().any():
    print(f"Range: {df['exit_date'].min()} to {df['exit_date'].max()}")

BEFORE: datetime64[ns] | Non-null: 49
AFTER: datetime64[ns] | NaT: 106
Range: 2015-12-25 00:00:00 to 2026-10-04 00:00:00

In [18]:
# Print the current dtype of 'salary' and a few sample raw values before cleaning
print(f"BEFORE: {df['salary'].dtype}")
for i in range(min(5, len(df))):
    # Display sample salary values for auditing
    print(f"  Row {i}: '{df['salary'].iloc[i]}'")

# Clean and convert 'salary' to numeric:
# 1) Ensure all values are strings for safe string operations
# 2) Remove commas used as thousands separators
# 3) Strip any leading/trailing whitespace
# 4) Convert to numeric, coercing unparseable values to NaN
df['salary'] = pd.to_numeric(
    df['salary'].astype(str).str.replace(',', '').str.strip(),
    errors='coerce'
)

# Print a summary after conversion: dtype, NaN count, min/max, and negative values
print(f"\nAFTER: {df['salary'].dtype} | NaN: {df['salary'].isna().sum()} | "
      f"Min: {df['salary'].min()} | Max: {df['salary'].max()} | "
      f"Negatives: {(df['salary']<0).sum()}")

BEFORE: object
  Row 0: '55,286.31'
  Row 1: '29408.75'
  Row 2: '35,393.84'
  Row 3: '39890.2'
  Row 4: '25532.92'

AFTER: float64 | NaN: 0 | Min: -38232.94 | Max: 416965.2 | Negatives: 4

In [19]:
# Print the current dtype of 'manager_id' before conversion
print(f"BEFORE: {df['manager_id'].dtype}")

# Convert 'manager_id' to numeric, coercing non-numeric strings (e.g., 'None', 'N/A') to NaN
df['manager_id'] = pd.to_numeric(df['manager_id'], errors='coerce')

# Print the new dtype, count of NaN (no manager assigned), and count of valid numeric IDs
print(f"AFTER: {df['manager_id'].dtype} | NaN: {df['manager_id'].isna().sum()} | Valid: {df['manager_id'].notna().sum()}")

BEFORE: float64
AFTER: float64 | NaN: 27 | Valid: 128

In [20]:
# Get all legitimate employee IDs in the dataset
valid_ids = df['employee_id'].unique()

# Print the overall range of employee IDs for context
print(f"Employee ID range: {df['employee_id'].min()} to {df['employee_id'].max()}")

# Identify rows where manager_id is not NaN but does not match any valid employee_id
invalid_mgr = df[(df['manager_id'].notna()) & (~df['manager_id'].isin(valid_ids))]

# Print how many invalid manager references exist
print(f"Invalid manager_ids: {len(invalid_mgr)}")

# If there are any invalid manager_ids, display them and their frequency, then fix them
if len(invalid_mgr) > 0:
    # Show details of employees with invalid manager references
    print(invalid_mgr[['employee_id', 'first_name', 'last_name', 'manager_id']].to_string())
    
    # Show counts of each invalid manager_id value
    print(f"Values: {invalid_mgr['manager_id'].value_counts().to_dict()}")

    # Overwrite invalid manager_id values with NaN to mark them as unknown
    df.loc[invalid_mgr.index, 'manager_id'] = np.nan
    
    # Confirm how many placeholders were corrected
    print(f"Converted {len(invalid_mgr)} placeholders to NaN")

# Print final summary: how many employees have no manager and how many have valid ones
print(f"\nResult: NaN: {df['manager_id'].isna().sum()} | Valid: {df['manager_id'].notna().sum()}")

# If there are any valid manager_ids left, print the range of valid IDs
if df['manager_id'].notna().any():
    print(f"Range: {df['manager_id'].min():.0f} to {df['manager_id'].max():.0f}")

Employee ID range: 1001 to 1150
Invalid manager_ids: 12
     employee_id first_name last_name  manager_id
23          1024       Sam     Naidoo    999999.0
26          1027       Liam    Smith     999999.0
50          1051      Alice    Brown     999999.0
51          1052        Mai    Naidoo    999999.0
56          1057        Que     Zuma     999999.0
72          1073     Alice      Smith    999999.0
87          1088      Abel     Nguyen    999999.0
104         1105      Grace    Nkosi     999999.0
119         1120      Faith   Ndlovu     999999.0
130         1131       Una     Ndlovu    999999.0
144         1145       Jane     Nkosi    999999.0
149         1150       Bob    Naidoo     999999.0
Values: {999999.0: 12}
Converted 12 placeholders to NaN

Result: NaN: 39 | Valid: 116
Range: 1001 to 1125

<div style="
background: linear-gradient(145deg, #f5eeff 0%, #e8d6f7 40%, #d4b8ee 70%, #ede0fa 100%);
border-radius:24px; padding:48px 48px 42px; position:relative; overflow:hidden;
box-shadow:0 30px 80px rgba(74,31,138,0.25), 0 8px 24px rgba(0,0,0,0.15);
max-width:780px; margin:auto; font-family:'Source Sans 3',sans-serif;">
<div style="position:absolute; top:0; right:0; bottom:0; left:0; background:radial-gradient(ellipse 60% 50% at 90% 10%, rgba(255,255,255,0.55) 0%, transparent 60%), radial-gradient(ellipse 40% 40% at 5% 90%, rgba(190,159,225,0.3) 0%, transparent 60%); pointer-events:none;"></div>
<div style="position:absolute; top:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
<p style="font-family:'Source Sans 3',sans-serif; font-size:10px; font-weight:600; letter-spacing:7px; text-transform:uppercase; color:#7b4db5; margin:0 0 10px 0; position:relative;">Phase 4</p>
<h2 style="font-family:'Playfair Display',serif; font-size:36px; font-weight:400; color:#2a0f5e; letter-spacing:2px; line-height:1.2; margin:0 0 10px 0; position:relative;">String Cleaning</h2>
<p style="font-family:'Source Sans 3',sans-serif; font-size:13px; font-weight:400; color:#9b70cc; letter-spacing:0.5px; margin:0 0 20px 0; position:relative;">Standardise every text column: trim whitespace, resolve phantom 'nan' strings, enforce consistent casing, and map all abbreviations and variants to canonical values across names, gender, department, currency, and location fields.</p>
<div style="height:1px; position:relative; background:linear-gradient(90deg, rgba(107,47,175,0.3), rgba(107,47,175,0.05));"></div>
<div style="position:absolute; bottom:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
</div>

In [21]:
# Select all columns with object (string) dtype
string_cols = df.select_dtypes(include='object').columns

# Loop through each string column to detect and remove leading/trailing whitespace
for col in string_cols:
    # Count how many values in this column have extra spaces at start or end
    spaces = df[col].apply(
        lambda x: str(x) != str(x).strip() if pd.notna(x) else False
    ).sum()

    # If any values had whitespace, print the column name and number trimmed
    if spaces > 0:
        print(f"  {col}: {spaces} trimmed")

    # Trim whitespace from all values in the column
    df[col] = df[col].astype(str).str.strip()

# Confirm that trimming is complete
print("All strings trimmed")

  first_name: 113 trimmed
  last_name: 79 trimmed
All strings trimmed

In [22]:
# Initialize a counter for how many phantom 'nan'/'None' strings we fix
n = 0  

# Loop through all string columns to identify and correct placeholder strings
for col in string_cols:
    # Count cells containing the literal strings 'nan' or 'None'
    c = (df[col] == 'nan').sum() + (df[col] == 'None').sum()

    # If any found, print the column name and count, and update total counter
    if c > 0:
        print(f"  {col}: {c}")  
        n += c

    # Replace the literal strings 'nan' and 'None' with proper NaN values
    df[col] = df[col].replace({'nan': np.nan, 'None': np.nan})

# Print the total number of replacements made
print(f"Converted {n} back to NaN")

  is_active: 49
  state: 53
  city: 49
  performance_score: 24
Converted 175 back to NaN

In [23]:
# Standardise first_name Casing

# Print the current counts of each first_name value before standardization
print("BEFORE:")
print(df['first_name'].value_counts())

# Convert all first names to Title Case (first letter uppercase, rest lowercase)
df['first_name'] = df['first_name'].str.title()

# Print the counts again to verify consistent formatting after conversion
print("\nAFTER:")
print(df['first_name'].value_counts())

BEFORE:
first_name
Faith    10
David    10
Una       8
Alice     8
Abel      7
Isaac     7
Chipo     7
Bob       7
Que       7
Vin       6
Sam       6
Ken       6
Liam      6
Nia       5
Henry     5
Esi       5
Zed       5
Yara      5
Rae       4
Tari      4
Oscar     4
Bea       4
Grace     4
Jane      4
Mai       3
Pat       3
Chad      3
Will      2
Name: count, dtype: int64

AFTER:
first_name
Faith    10
David    10
Una       8
Alice     8
Abel      7
Isaac     7
Chipo     7
Bob       7
Que       7
Vin       6
Sam       6
Ken       6
Liam      6
Nia       5
Henry     5
Esi       5
Zed       5
Yara      5
Rae       4
Tari      4
Oscar     4
Bea       4
Grace     4
Jane      4
Mai       3
Pat       3
Chad      3
Will      2
Name: count, dtype: int64

In [24]:
# Standardise last_name Casing
# Print the current counts of each last_name value before standardization
print("BEFORE:")
print(df['last_name'].value_counts())

# Convert all last names to Title Case (first letter uppercase, rest lowercase)
df['last_name'] = df['last_name'].str.title()

# Print the counts again to verify consistent formatting after conversion
print("\nAFTER:")
print(df['last_name'].value_counts())

BEFORE:
last_name
Nguyen      17
Naidoo      15
Zuma        13
Nkosi       13
Brown       12
Khan        12
Govender    11
Pillay      10
Ndlovu      10
Smith        9
Mthembu      9
Dlamini      9
van Wyk      8
Moyo         7
Name: count, dtype: int64

AFTER:
last_name
Nguyen      17
Naidoo      15
Zuma        13
Nkosi       13
Brown       12
Khan        12
Govender    11
Pillay      10
Ndlovu      10
Smith        9
Mthembu      9
Dlamini      9
Van Wyk      8
Moyo         7
Name: count, dtype: int64

In [25]:
#  Standardise email to Lowercase

# Print the first 10 email values before standardization
print("BEFORE:")
print(df['email'].head(10))

# Convert all emails to lowercase and remove any leading/trailing whitespace
df['email'] = df['email'].str.lower().str.strip()

# Print the first 10 email values after standardization to verify changes
print("\nAFTER:")
print(df['email'].head(10))

BEFORE:
0    ken.naidoo@example.com
1        sam.smith@mail.com
2    oscar.mthembu@mail.com
3         sam.brown@example
4    faith.mthembu@mail.com
5       esi.dlaminimail.com
6    david.zuma@example.com
7      david.nguyen@example
8      liam.naidoo@mail.com
9      chipo.nkosi@mail.com
Name: email, dtype: object

AFTER:
0    ken.naidoo@example.com
1        sam.smith@mail.com
2    oscar.mthembu@mail.com
3         sam.brown@example
4    faith.mthembu@mail.com
5       esi.dlaminimail.com
6    david.zuma@example.com
7      david.nguyen@example
8      liam.naidoo@mail.com
9      chipo.nkosi@mail.com
Name: email, dtype: object

In [26]:
# Standardise gender Values 

# Print the counts of all gender values (including NaN) before mapping
print("BEFORE:")
print(df['gender'].value_counts(dropna=False))

# Define a dictionary mapping known variants to standardized labels
gender_map = {
    'male'  : 'Male',
    'm'     : 'Male',
    'female': 'Female',
    'f'     : 'Female',
    'other' : 'Other'
}

# Save a copy of the original column to preserve any unmapped values
orig = df['gender'].copy()

# Normalize to lowercase and map each value using the dictionary; unmapped values become NaN
df['gender'] = df['gender'].str.lower().map(gender_map)

# Restore any original values that were not recognized by the map (preventing accidental NaN)
unmapped = df['gender'].isna() & orig.notna()
if unmapped.sum() > 0:
    df.loc[unmapped, 'gender'] = orig[unmapped]

# Print the counts of all gender values after standardization
print("\nAFTER:")
print(df['gender'].value_counts(dropna=False))

BEFORE:
gender
M         37
Male      34
Female    30
F         29
Other     25
Name: count, dtype: int64

AFTER:
gender
Male      71
Female    59
Other     25
Name: count, dtype: int64

In [27]:
# Standardise department Values

print("BEFORE:")
print(df['department'].value_counts(dropna=False))

# Comprehensive mapping covering abbreviations, shorthand, and casing variants.
# Every key is lowercase to match after .str.lower().
dept_map = {
    'eng'                 : 'Engineering',
    'engineering'         : 'Engineering',
    'hr'                  : 'Human Resources',
    'h.r.'                : 'Human Resources',
    'human resources'     : 'Human Resources',
    'sales'               : 'Sales',
    'ops'                 : 'Operations',
    'operations'          : 'Operations',
    'it'                  : 'Information Technology',
    'information technology': 'Information Technology',
    'fin'                 : 'Finance',
    'finance'             : 'Finance'
}

orig = df['department'].copy()
df['department'] = df['department'].str.lower().map(dept_map)

# Restore any values the map did not recognise so we don't silently lose data.
unmapped = df['department'].isna() & orig.notna()
if unmapped.sum() > 0:
    df.loc[unmapped, 'department'] = orig[unmapped]

print("\nAFTER:")
print(df['department'].value_counts(dropna=False))

BEFORE:
department
H.R.                      19
Engineering               16
Information Technology    15
IT                        14
Finance                   13
HR                        12
Sales                     12
Eng                       12
Ops                       10
sales                     10
Human Resources            9
Operations                 7
FIN                        6
Name: count, dtype: int64

AFTER:
department
Human Resources           40
Information Technology    29
Engineering               28
Sales                     22
Finance                   19
Operations                17
Name: count, dtype: int64

In [28]:
# Standardise job_title Casing

# Job titles in raw HR exports often arrive in inconsistent casing:
# 'senior engineer', 'Senior Engineer', 'SENIOR ENGINEER'.
# Title Case normalises all variants so groupby and reporting work correctly.
print("BEFORE:")
print(df['job_title'].value_counts(dropna=False))

df['job_title'] = df['job_title'].str.title()

print("\nAFTER:")
print(df['job_title'].value_counts(dropna=False))

BEFORE:
job_title
Data Scientist    21
Senior Analyst    20
Manager           20
Clerk             20
Engineer          16
Analyst           16
Sales Rep         15
Accountant        15
HR Officer        12
Name: count, dtype: int64

AFTER:
job_title
Data Scientist    21
Senior Analyst    20
Manager           20
Clerk             20
Engineer          16
Analyst           16
Sales Rep         15
Accountant        15
Hr Officer        12
Name: count, dtype: int64

In [29]:
# Standardise currency Values

print("BEFORE:")
print(df['currency'].value_counts(dropna=False))

# Map currency symbols and abbreviations currency codes instead of letters.
curr_map = {
    'r'  : 'ZAR',
    'zar': 'ZAR',
    '£'  : 'GBP',
    'gbp': 'GBP',
    '$'  : 'USD',
    'usd': 'USD'
}

orig = df['currency'].copy()
df['currency'] = df['currency'].str.lower().map(curr_map)

# Restore unrecognised values to avoid data loss.
unmapped = df['currency'].isna() & orig.notna()
if unmapped.sum() > 0:
    df.loc[unmapped, 'currency'] = orig[unmapped]

print("\nAFTER:")
print(df['currency'].value_counts(dropna=False))

BEFORE:
currency
ZAR    36
R      30
GBP    25
$      22
USD    22
£      20
Name: count, dtype: int64

AFTER:
currency
ZAR    66
GBP    45
USD    44
Name: count, dtype: int64

In [30]:
# Standardise country Values

print("BEFORE:")
print(df['country'].value_counts(dropna=False))

# Create a dictonary map for every known country abbreviation and variant to a full, consistent name.
# convert to full department names  are preferred over codes for readability in HR reporting.
country_map = {
    'u.k.'         : 'United Kingdom',
    'uk'           : 'United Kingdom',
    'united kingdom': 'United Kingdom',
    'sa'           : 'South Africa',
    'za'           : 'South Africa',
    'south africa' : 'South Africa',
    'usa'          : 'United States',
    'united states': 'United States'
}

orig = df['country'].copy()
df['country'] = df['country'].str.lower().map(country_map)

# Restore any values not captured by the map.
unmapped = df['country'].isna() & orig.notna()
if unmapped.sum() > 0:
    df.loc[unmapped, 'country'] = orig[unmapped]

print("\nAFTER:")
print(df['country'].value_counts(dropna=False))

BEFORE:
country
U.K.              25
United Kingdom    18
South Africa      18
United States     18
ZA                17
UK                16
SA                15
USA               15
south-africa      13
Name: count, dtype: int64

AFTER:
country
United Kingdom    59
South Africa      50
United States     33
south-africa      13
Name: count, dtype: int64

In [31]:
# Clean state Column

print("BEFORE:")
print(df['state'].value_counts(dropna=False))

# 'south-africa' is a country name that was incorrectly placed in the state column.
# It carries no meaningful province/state information so we replace it with NaN.
# We will attempt to infer the correct state from the city column in Cell 35.
df['state'] = df['state'].replace('south-africa', np.nan)

# Apply Title Case to ensure consistent formatting across all state names
# (e.g. 'gauteng' -> 'Gauteng', 'western cape' -> 'Western Cape').
df['state'] = df['state'].str.title()

print("\nAFTER:")
print(df['state'].value_counts(dropna=False))

BEFORE:
state
NaN             53
KZN             31
Gauteng         30
Western Cape    24
Limpopo         17
Name: count, dtype: int64

AFTER:
state
NaN             53
Kzn             31
Gauteng         30
Western Cape    24
Limpopo         17
Name: count, dtype: int64

In [32]:
#Infer Missing State From City

# South African cities we know the province to it is in with certainty.
# Create a dictionary maps with each city to its correct province/state.
# We use this to recover state values that were missing or incorrectly entered.
city_to_state = {
    'Durban'      : 'KZN',
    'Pretoria'    : 'Gauteng',
    'Polokwane'   : 'Limpopo',
    'Cape Town'   : 'Western Cape',
    'Johannesburg': 'Gauteng'
}

# For each city-state pair, build a boolean mask targeting rows where:
#   - the city matches our lookup key
#   - the state is currently missing (NaN)
# Only fill rows that satisfy BOTH conditions to avoid overwriting valid data.
for city, state in city_to_state.items():
    mask = (df['city'] == city) & (df['state'].isna())
    if mask.sum() > 0:
        df.loc[mask, 'state'] = state
        print(f"  {city} -> {state}: {mask.sum()}")

# Report any rows where state is still missing after the city-based fill.
# These may be international employees where province inference is not possible.
still = df[df['state'].isna() & df['city'].notna()]
if len(still) > 0:
    print(f"Still missing: {len(still)}")
    print(still[['employee_id', 'city', 'country']].to_string())

print(f"\n{df['state'].value_counts(dropna=False)}")

  Durban -> KZN: 4
  Pretoria -> Gauteng: 6
  Polokwane -> Limpopo: 11
  Cape Town -> Western Cape: 9
  Johannesburg -> Gauteng: 7

state
Gauteng         43
Western Cape    33
Kzn             31
Limpopo         28
NaN             16
KZN              4
Name: count, dtype: int64

In [33]:
# Standardise city Casing

# Apply Title Case to city names for the same reason as names and departments —
# 'cape town', 'Cape Town', and 'CAPE TOWN' must resolve to one canonical form
# so that groupby operations and location-based reporting count them correctly.
df['city'] = df['city'].str.title()

print(df['city'].value_counts(dropna=False))

city
NaN             49
Cape Town       29
Polokwane       23
Johannesburg    21
Durban          20
Pretoria        13
Name: count, dtype: int64

In [34]:
#  Audit performance_score Values
# Display all unique performance_score values along with their counts, including NaN
print(df['performance_score'].value_counts(dropna=False))

performance_score
D      39
A      37
C      30
B      25
NaN    24
Name: count, dtype: int64

<div style="
background: linear-gradient(145deg, #f5eeff 0%, #e8d6f7 40%, #d4b8ee 70%, #ede0fa 100%);
border-radius:24px; padding:48px 48px 42px; position:relative; overflow:hidden;
box-shadow:0 30px 80px rgba(74,31,138,0.25), 0 8px 24px rgba(0,0,0,0.15);
max-width:780px; margin:auto; font-family:'Source Sans 3',sans-serif;">
<div style="position:absolute; top:0; right:0; bottom:0; left:0; background:radial-gradient(ellipse 60% 50% at 90% 10%, rgba(255,255,255,0.55) 0%, transparent 60%), radial-gradient(ellipse 40% 40% at 5% 90%, rgba(190,159,225,0.3) 0%, transparent 60%); pointer-events:none;"></div>
<div style="position:absolute; top:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
<p style="font-family:'Source Sans 3',sans-serif; font-size:10px; font-weight:600; letter-spacing:7px; text-transform:uppercase; color:#7b4db5; margin:0 0 10px 0; position:relative;">Phase 5</p>
<h2 style="font-family:'Playfair Display',serif; font-size:36px; font-weight:400; color:#2a0f5e; letter-spacing:2px; line-height:1.2; margin:0 0 10px 0; position:relative;">Missing Values</h2>
<p style="font-family:'Source Sans 3',sans-serif; font-size:13px; font-weight:400; color:#9b70cc; letter-spacing:0.5px; margin:0 0 20px 0; position:relative;">Resolve remaining nulls with deliberate, documented decisions — filling where logic permits, and consciously leaving gaps where imputation would introduce false data. Every choice here is a data governance decision, not just a technical one.</p>
<div style="height:1px; position:relative; background:linear-gradient(90deg, rgba(107,47,175,0.3), rgba(107,47,175,0.05));"></div>
<div style="position:absolute; bottom:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
</div>

In [35]:
# Standardise and Fill is_active 

# Print the counts of all is_active values (including NaN) before standardization
print("BEFORE:")
print(df['is_active'].value_counts(dropna=False))

# Convert all values to strings, strip whitespace, and uppercase for consistent mapping
df['is_active'] = df['is_active'].astype(str).str.strip().str.upper()

# Map normalized strings to Python booleans; unmapped values become NaN
df['is_active'] = df['is_active'].map({'TRUE': True, 'FALSE': False})

# Count how many NaN values remain before filling
before = df['is_active'].isna().sum()

# Fill NaN values: if exit_date exists, employee has left → False
df.loc[(df['is_active'].isna()) & (df['exit_date'].notna()), 'is_active'] = False

# Fill NaN values: if exit_date is missing, employee likely still active → True
df.loc[(df['is_active'].isna()) & (df['exit_date'].isna()),  'is_active'] = True

# Print how many missing values were filled
print(f"Filled {before - df['is_active'].isna().sum()} missing")

# Print the counts of all is_active values after standardization and filling
print("\nAFTER:")
print(df['is_active'].value_counts(dropna=False))

BEFORE:
is_active
True     53
False    53
NaN      49
Name: count, dtype: int64
Filled 49 missing

AFTER:
is_active
False    102
True      53
Name: count, dtype: int64

In [36]:
# Fill Missing department Values

# Count how many department values are missing.
m = df['department'].isna().sum()

if m > 0:
    # Fill with the mode (most frequently occurring department).
    # This is a last resort — we use it only when no better signal exists.
    # mode() returns a Series so we index [0] to get the top value as a scalar.
    df['department'] = df['department'].fillna(df['department'].mode()[0])
    print(f"Filled {m} with mode")
else:
    print("No missing departments")

No missing departments

In [37]:
# Assess Missing exit_date Values

# Missing exit_date is not always an error, it is expected for active employees.
# We break the missing count into two meaningful groups to confirm this.
print(f"Missing exit_dates: {df['exit_date'].isna().sum()}")

# Active employees with no exit date, mean that they are still employed
print(f"  Active no exit: {df[(df['is_active']==True) & (df['exit_date'].isna())].shape[0]} (expected)")

# Inactive employees with no exit date is a data gap
print(f"  Inactive no exit: {df[(df['is_active']==False) & (df['exit_date'].isna())].shape[0]}")

print("DECISION: Leave as NaT")

Missing exit_dates: 106
  Active no exit: 53 (expected)
  Inactive no exit: 53
DECISION: Leave as NaT

In [38]:
# Assess Missing salary Values 
# Count and display how many salary values are still missing (NaN) after cleaning
print(f"Missing salaries: {df['salary'].isna().sum()} ")

Missing salaries: 0

In [39]:
# Assess Missing currency Values

# Check how many rows have no currency value.
m = df['currency'].isna().sum()

# If any are missing, display the affected rows so we can assess whether
# the country field could help us infer the correct currency.
if m > 0:
    print(df[df['currency'].isna()][['employee_id', 'first_name', 'country', 'salary']])

# Decision: leave as NaN. Guessing a currency from country alone could be
# wrong for international employees paid in a foreign currency.
print(f"Missing currency: {m} ")

Missing currency: 0

In [40]:
# Document All Remaining Intentional NaN Fields

# Print counts of NaN values for columns intentionally left incomplete, as an audit record
print(
    f"state: {df['state'].isna().sum()} | "
    f"city: {df['city'].isna().sum()} | "
    f"manager_id: {df['manager_id'].isna().sum()} | "
    f"performance: {df['performance_score'].isna().sum()} "
    f"— All left as NaN"
)

state: 16 | city: 49 | manager_id: 39 | performance: 24 — All left as NaN

In [41]:
# Full Column-by-Column Missing Value Summary

# Iterate every column in the cleaned DataFrame and print its missing value count.
# Columns with 0 missing values are labelled CLEAN for instant readability.
# Columns with remaining NaN show the exact count so nothing is hidden.
# This is the closing audit of Phase 5 — a documented sign-off on missing data.
for col in df.columns:
    m = df[col].isna().sum()
    print(f"  {col:25s} {'CLEAN' if m == 0 else f'{m} missing'}")

  employee_id               CLEAN
  first_name                CLEAN
  last_name                 CLEAN
  email                     CLEAN
  gender                    CLEAN
  department                CLEAN
  job_title                 CLEAN
  hire_date                 CLEAN
  exit_date                 106 missing
  is_active                 CLEAN
  salary                    CLEAN
  currency                  CLEAN
  country                   CLEAN
  state                     16 missing
  city                      49 missing
  manager_id                39 missing
  performance_score         24 missing

<div style="
background: linear-gradient(145deg, #f5eeff 0%, #e8d6f7 40%, #d4b8ee 70%, #ede0fa 100%);
border-radius:24px; padding:48px 48px 42px; position:relative; overflow:hidden;
box-shadow:0 30px 80px rgba(74,31,138,0.25), 0 8px 24px rgba(0,0,0,0.15);
max-width:780px; margin:auto; font-family:'Source Sans 3',sans-serif;">
<div style="position:absolute; top:0; right:0; bottom:0; left:0; background:radial-gradient(ellipse 60% 50% at 90% 10%, rgba(255,255,255,0.55) 0%, transparent 60%), radial-gradient(ellipse 40% 40% at 5% 90%, rgba(190,159,225,0.3) 0%, transparent 60%); pointer-events:none;"></div>
<div style="position:absolute; top:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
<p style="font-family:'Source Sans 3',sans-serif; font-size:10px; font-weight:600; letter-spacing:7px; text-transform:uppercase; color:#7b4db5; margin:0 0 10px 0; position:relative;">Phase 6</p>
<h2 style="font-family:'Playfair Display',serif; font-size:36px; font-weight:400; color:#2a0f5e; letter-spacing:2px; line-height:1.2; margin:0 0 10px 0; position:relative;">Deduplication</h2>
<p style="font-family:'Source Sans 3',sans-serif; font-size:13px; font-weight:400; color:#9b70cc; letter-spacing:0.5px; margin:0 0 20px 0; position:relative;">Remove duplicate records to ensure each employee appears exactly once. Duplicate rows distort every downstream metric — headcount, average salary, turnover rate — so this step is critical before any analysis is performed.</p>
<div style="height:1px; position:relative; background:linear-gradient(90deg, rgba(107,47,175,0.3), rgba(107,47,175,0.05));"></div>
<div style="position:absolute; bottom:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
</div>

In [42]:
# Print the number of rows in the DataFrame before removing duplicates
print(f"Before: {len(df)}")

# Count how many rows share the same employee_id (after the first occurrence)
dupes = df.duplicated(subset='employee_id', keep='first').sum()

# If there are duplicate employee_id rows, remove all but the first occurrence
if dupes > 0:
    df = df.drop_duplicates(subset='employee_id', keep='first')
    print(f"Removed {dupes}")
else:
    print("No duplicates")

# Second pass: drop rows that are exact duplicates across all columns and reset the index
df = df.drop_duplicates().reset_index(drop=True)

# Print the number of rows after duplicate removal
print(f"After: {len(df)}")

Before: 155
Removed 5
After: 150

<div style="
background: linear-gradient(145deg, #f5eeff 0%, #e8d6f7 40%, #d4b8ee 70%, #ede0fa 100%);
border-radius:24px; padding:48px 48px 42px; position:relative; overflow:hidden;
box-shadow:0 30px 80px rgba(74,31,138,0.25), 0 8px 24px rgba(0,0,0,0.15);
max-width:780px; margin:auto; font-family:'Source Sans 3',sans-serif;">
<div style="position:absolute; top:0; right:0; bottom:0; left:0; background:radial-gradient(ellipse 60% 50% at 90% 10%, rgba(255,255,255,0.55) 0%, transparent 60%), radial-gradient(ellipse 40% 40% at 5% 90%, rgba(190,159,225,0.3) 0%, transparent 60%); pointer-events:none;"></div>
<div style="position:absolute; top:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
<p style="font-family:'Source Sans 3',sans-serif; font-size:10px; font-weight:600; letter-spacing:7px; text-transform:uppercase; color:#7b4db5; margin:0 0 10px 0; position:relative;">Phase 7</p>
<h2 style="font-family:'Playfair Display',serif; font-size:36px; font-weight:400; color:#2a0f5e; letter-spacing:2px; line-height:1.2; margin:0 0 10px 0; position:relative;">Data Validation</h2>
<p style="font-family:'Source Sans 3',sans-serif; font-size:13px; font-weight:400; color:#9b70cc; letter-spacing:0.5px; margin:0 0 20px 0; position:relative;">Verify that values are not just present but logically correct — valid email formats, positive salaries, chronologically sound dates, and salary figures within plausible ranges. Cleaning removes dirt; validation ensures what remains makes sense.</p>
<div style="height:1px; position:relative; background:linear-gradient(90deg, rgba(107,47,175,0.3), rgba(107,47,175,0.05));"></div>
<div style="position:absolute; bottom:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
</div>

In [43]:
# Check whether each email matches a basic pattern (something@something.something)
df['email_valid'] = df['email'].apply(
    # Convert to string, match regex, return True if valid, False otherwise; NaN treated as False
    lambda x: bool(re.match(r'^.+@.+\..+', str(x))) if pd.notna(x) else False
)

# Extract all rows where the email was invalid
inv = df[df['email_valid'] == False]

# Print summary counts of valid and invalid emails
print(f"Valid: {df['email_valid'].sum()} | Invalid: {len(inv)}")

# If there are invalid emails, display their employee details for review
if len(inv) > 0:
    print(inv[['employee_id', 'first_name', 'last_name', 'email']])

Valid: 103 | Invalid: 47
     employee_id first_name last_name                     email
3           1004        Sam     Brown         sam.brown@example
5           1006        Esi   Dlamini       esi.dlaminimail.com
7           1008      David    Nguyen      david.nguyen@example
10          1011        Mai   Van Wyk       mai.van wykmail.com
15          1016        Ken      Khan          ken.khan@example
16          1017        Esi      Khan     esi.khancompany.co.za
17          1018        Esi      Moyo     esi.moyocompany.co.za
19          1020        Vin    Nguyen   vin.nguyencompany.co.za
23          1024        Sam    Naidoo        sam.naidoo@example
25          1026      Alice    Naidoo      alice.naidoo@example
26          1027       Liam     Smith     liam.smithexample.com
32          1033      Isaac     Nkosi        isaac.nkosiexample
34          1035        Bob    Pillay        bob.pillay@example
39          1040        Bob   Dlamini       bob.dlamini@example
42          1043      David    Nguyen      david.nguyen@example
45          1046        Que      Zuma          que.zuma@example
47          1048       Chad    Nguyen       chad.nguyen@example
49          1050        Nia      Khan          nia.khan@example
50          1051      Alice     Brown    alice.brownexample.com
51          1052        Mai    Naidoo     mai.naidooexample.com
55          1056      David     Nkosi    david.nkosiexample.com
61          1062      Isaac   Mthembu     isaac.mthembu@example
69          1070        Pat      Zuma          pat.zuma@example
78          1079       Yara      Khan         yara.khan@example
84          1085        Nia    Pillay        nia.pillay@example
86          1087        Zed    Ndlovu     zed.ndlovuexample.com
90          1091      David      Khan        david.khan@example
91          1092       Tari   Dlamini      tari.dlamini@example
92          1093       Jane    Pillay       jane.pillay@example
93          1094       Liam    Naidoo       liam.naidoo@example
95          1096        Bea   Mthembu       bea.mthembu@example
101         1102      Henry     Nkosi  henry.nkosicompany.co.za
104         1105      Grace     Nkosi       grace.nkosi@example
105         1106       Yara    Nguyen    yara.nguyenexample.com
111         1112      Oscar   Dlamini     oscar.dlamini@example
112         1113      Alice    Ndlovu      alice.ndlovumail.com
114         1115       Will     Nkosi        will.nkosi@example
118         1119      David      Zuma        david.zuma@example
121         1122        Zed    Nguyen        zed.nguyen@example
125         1126      Faith    Pillay      faith.pillay@example
126         1127      Grace     Nkosi    grace.nkosiexample.com
127         1128        Bea     Smith         bea.smith@example
133         1134        Vin     Smith         vin.smith@example
141         1142       Yara      Zuma         yara.zuma@example
142         1143        Rae      Moyo          rae.moyo@example
145         1146       Jane     Nkosi        jane.nkosi@example
149         1150        Bob    Naidoo        bob.naidoo@example

In [44]:
# Identify rows where salary is negative
neg = df[df['salary'] < 0]

# Print the count of negative salary entries
print(f"Negative salaries: {len(neg)}")

# If there are negative salaries, inspect and correct them
if len(neg) > 0:
    # Show employee_id, first_name, and salary before correction
    print("BEFORE:")
    print(neg[['employee_id', 'first_name', 'salary']])

    # Replace negative salaries with their absolute value, leaving NaN unchanged
    df['salary'] = df['salary'].apply(
        lambda x: abs(x) if pd.notna(x) and x < 0 else x
    )

    # Show the corrected salary values for the affected rows
    print("AFTER:")
    print(df.loc[neg.index, ['employee_id', 'first_name', 'salary']])

Negative salaries: 4
BEFORE:
    employee_id first_name    salary
30         1031      Henry -26089.36
48         1049        Que -38232.94
86         1087        Zed -31403.47
95         1096        Bea -34329.59
AFTER:
    employee_id first_name    salary
30         1031      Henry  26089.36
48         1049        Que  38232.94
86         1087        Zed  31403.47
95         1096        Bea  34329.59

In [45]:
# Identify rows where exit_date is earlier than hire_date, which is impossible
bad = df[
    (df['exit_date'].notna()) &   # exit_date exists
    (df['hire_date'].notna()) &   # hire_date exists
    (df['exit_date'] < df['hire_date'])  # exit_date is before hire_date
]

# Print how many rows have exit dates before hire dates
print(f"Exit before hire: {len(bad)}")

# If any impossible sequences are found, inspect and correct them
if len(bad) > 0:
    # Display employee_id, hire_date, and exit_date for review
    print(bad[['employee_id', 'hire_date', 'exit_date']])

    # Set the invalid exit_date values to NaT to indicate missing/unknown
    df.loc[bad.index, 'exit_date'] = pd.NaT

Exit before hire: 1
     employee_id  hire_date  exit_date
118         1119 2021-09-12 2021-09-10

In [46]:
# Identify Suspicious Salary Outliers 

# Print basic salary statistics to understand the overall distribution
print(f"Min: {df['salary'].min()} | Max: {df['salary'].max()} | Median: {df['salary'].median():.2f}")

# Identify salaries that are suspiciously high (≥ 999,999), often placeholders or data entry errors
high = df[df['salary'] >= 999999]

# If any suspicious salaries are found, print the count and relevant employee details
if len(high) > 0:
    print(f"Suspicious: {len(high)}")
    print(high[['employee_id', 'job_title', 'salary']])

Min: 7540.22 | Max: 416965.2 | Median: 33976.46

<div style="
background: linear-gradient(145deg, #f5eeff 0%, #e8d6f7 40%, #d4b8ee 70%, #ede0fa 100%);
border-radius:24px; padding:48px 48px 42px; position:relative; overflow:hidden;
box-shadow:0 30px 80px rgba(74,31,138,0.25), 0 8px 24px rgba(0,0,0,0.15);
max-width:780px; margin:auto; font-family:'Source Sans 3',sans-serif;">
<div style="position:absolute; top:0; right:0; bottom:0; left:0; background:radial-gradient(ellipse 60% 50% at 90% 10%, rgba(255,255,255,0.55) 0%, transparent 60%), radial-gradient(ellipse 40% 40% at 5% 90%, rgba(190,159,225,0.3) 0%, transparent 60%); pointer-events:none;"></div>
<div style="position:absolute; top:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
<p style="font-family:'Source Sans 3',sans-serif; font-size:10px; font-weight:600; letter-spacing:7px; text-transform:uppercase; color:#7b4db5; margin:0 0 10px 0; position:relative;">Phase 8</p>
<h2 style="font-family:'Playfair Display',serif; font-size:36px; font-weight:400; color:#2a0f5e; letter-spacing:2px; line-height:1.2; margin:0 0 10px 0; position:relative;">Final Review</h2>
<p style="font-family:'Source Sans 3',sans-serif; font-size:13px; font-weight:400; color:#9b70cc; letter-spacing:0.5px; margin:0 0 20px 0; position:relative;">A comprehensive end-to-end review of the fully cleaned dataset before export. We verify shape, value distributions, and salary range, preview the final records, then write the cleaned data to a new CSV file ready for analysis.</p>
<div style="height:1px; position:relative; background:linear-gradient(90deg, rgba(107,47,175,0.3), rgba(107,47,175,0.05));"></div>
<div style="position:absolute; bottom:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
</div>

In [47]:
#Final Dataset Review

# Print the shape of the cleaned DataFrame to verify rows and columns
print(f"Shape: {df.shape}")

# Iterate through key categorical columns and print value counts for each
for label, col in [
    ("Dept",     "department"),
    ("Currency", "currency"),
    ("Gender",   "gender"),
    ("Country",  "country"),
    ("Active",   "is_active"),
    ("Jobs",     "job_title")
]:
    # Print the column label and the distribution of values
    print(f"\n{label}:\n{df[col].value_counts()}")

# Perform a final sanity check on the salary column: min, max, and mean
print(f"\nSalary — Min: {df['salary'].min()} | Max: {df['salary'].max()} | Mean: {df['salary'].mean():.2f}")

Shape: (150, 18)

Dept:
department
Human Resources           39
Information Technology    29
Engineering               27
Sales                     20
Finance                   18
Operations                17
Name: count, dtype: int64

Currency:
currency
ZAR    63
USD    44
GBP    43
Name: count, dtype: int64

Gender:
gender
Male      67
Female    58
Other     25
Name: count, dtype: int64

Country:
country
United Kingdom    57
South Africa      50
United States     30
south-africa      13
Name: count, dtype: int64

Active:
is_active
False    98
True     52
Name: count, dtype: int64

Jobs:
job_title
Data Scientist    20
Clerk             20
Senior Analyst    18
Manager           18
Engineer          16
Analyst           16
Sales Rep         15
Accountant        15
Hr Officer        12
Name: count, dtype: int64

Salary — Min: 7540.22 | Max: 416965.2 | Mean: 41154.88

In [48]:
#  Preview Final Cleaned Dataset 

df.head(10)

,employee_id,first_name,last_name,email,gender,department,job_title,hire_date,exit_date,is_active,salary,currency,country,state,city,manager_id,performance_score,email_valid
0,1001,Ken,Naidoo,ken.naidoo@example.com,Male,Human Resources,Sales Rep,2017-05-29,NaT,True,55286.31,GBP,south-africa,Western Cape,NaN,NaN,NaN,True
1,1002,Sam,Smith,sam.smith@mail.com,Male,Human Resources,Sales Rep,2016-04-27,NaT,True,29408.75,GBP,south-africa,Gauteng,Johannesburg,1001.0,C,True
2,1003,Oscar,Mthembu,oscar.mthembu@mail.com,Male,Operations,Engineer,2015-12-02,NaT,False,35393.84,USD,South Africa,Kzn,Cape Town,NaN,NaN,True
3,1004,Sam,Brown,sam.brown@example,Male,Sales,Senior Analyst,2016-01-19,NaT,True,39890.20,GBP,United States,Kzn,NaN,1003.0,C,False
4,1005,Faith,Mthembu,faith.mthembu@mail.com,Male,Human Resources,Engineer,2019-06-18,2022-01-22,False,25532.92,GBP,United Kingdom,Limpopo,Polokwane,NaN,B,True
5,1006,Esi,Dlamini,esi.dlaminimail.com,Male,Information Technology,Manager,2017-12-12,NaT,False,35024.79,GBP,South Africa,Limpopo,NaN,1005.0,D,False
6,1007,David,Zuma,david.zuma@example.com,Male,Sales,Manager,2016-03-26,2017-02-28,False,34989.32,ZAR,United Kingdom,Western Cape,NaN,1003.0,A,True
7,1008,David,Nguyen,david.nguyen@example,Other,Human Resources,Senior Analyst,2018-11-04,NaT,True,13943.31,GBP,United States,Gauteng,NaN,1006.0,NaN,False
8,1009,Liam,Naidoo,liam.naidoo@mail.com,Other,Operations,Engineer,2017-09-07,2020-09-01,False,47211.90,USD,United Kingdom,Western Cape,NaN,1006.0,C,True
9,1010,Chipo,Nkosi,chipo.nkosi@mail.com,Male,Sales,Analyst,2020-05-17,NaT,True,42205.98,USD,South Africa,Limpopo,NaN,1002.0,D,True

In [49]:
#  Export Cleaned Dataset to CSV 

# Drop the temporary 'email_valid' column used for validation; ignore if it doesn't exist
df_save = df.drop(columns=['email_valid'], errors='ignore')

# Save the cleaned DataFrame to a CSV file without writing the index column
df_save.to_csv('Week-3-Employee-Data_CLEANED.csv', index=False)

# Print confirmation of how many records and columns were saved
print(f"SAVED: {len(df_save)} records, {df_save.shape[1]} columns")

SAVED: 150 records, 17 columns

<div style="
background: linear-gradient(145deg, #f5eeff 0%, #e8d6f7 40%, #d4b8ee 70%, #ede0fa 100%);
border-radius:24px; padding:48px 48px 42px; position:relative; overflow:hidden;
box-shadow:0 30px 80px rgba(74,31,138,0.25), 0 8px 24px rgba(0,0,0,0.15);
max-width:780px; margin:auto; font-family:'Source Sans 3',sans-serif;">
<div style="position:absolute; top:0; right:0; bottom:0; left:0; background:radial-gradient(ellipse 60% 50% at 90% 10%, rgba(255,255,255,0.55) 0%, transparent 60%), radial-gradient(ellipse 40% 40% at 5% 90%, rgba(190,159,225,0.3) 0%, transparent 60%); pointer-events:none;"></div>
<div style="position:absolute; top:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
<p style="font-family:'Source Sans 3',sans-serif; font-size:10px; font-weight:600; letter-spacing:7px; text-transform:uppercase; color:#7b4db5; margin:0 0 10px 0; position:relative;">Phase 9</p>
<h2 style="font-family:'Playfair Display',serif; font-size:36px; font-weight:400; color:#2a0f5e; letter-spacing:2px; line-height:1.2; margin:0 0 10px 0; position:relative;">HR KPIs</h2>
<p style="font-family:'Source Sans 3',sans-serif; font-size:13px; font-weight:400; color:#9b70cc; letter-spacing:0.5px; margin:0 0 20px 0; position:relative;">With a fully cleaned dataset in place, we compute core Human Resources key performance indicators — headcount, hiring trends, compensation benchmarks, tenure, turnover, top managers by team size, and email data quality — demonstrating the analytical value that clean data unlocks.</p>
<div style="height:1px; position:relative; background:linear-gradient(90deg, rgba(107,47,175,0.3), rgba(107,47,175,0.05));"></div>
<div style="position:absolute; bottom:0; left:0; right:0; height:3px; background:linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);"></div>
</div>

In [50]:
# KPI — Active vs Inactive Headcount 

# Filter the DataFrame to rows where is_active is True to get current headcount.
a = df[df['is_active'] == True].shape[0]

# Total employee count (active + former employees).
t = len(df)


# print the summary
print(f"Active: {a} | Inactive: {t - a} | Total: {t} | Rate: {a / t * 100:.1f}%")

Active: 52 | Inactive: 98 | Total: 150 | Rate: 34.7%

In [51]:
#  KPI — Hiring Volume by Year 

# Extract the year from hire_date and store it in a new column 'hire_year'
df['hire_year'] = df['hire_date'].dt.year

# Count how many employees were hired each year and sort the counts chronologically
h = df['hire_year'].value_counts().sort_index()

# Print each year and the corresponding number of hires
for y, c in h.items():
    print(f"  {int(y)}: {c}")

# Print the year with the highest number of hires (peak hiring year) and its count
print(f"\nPeak: {int(h.idxmax())} ({h.max()})")

  2015: 18
  2016: 18
  2017: 27
  2018: 20
  2019: 18
  2020: 13
  2021: 13
  2022: 23

Peak: 2017 (27)

In [52]:
# KPI — Salary Benchmarks by Department and Currency 

# Group the DataFrame by department and currency to compare like-for-like salaries
r = df.groupby(['department', 'currency'])['salary'].agg(['mean', 'median', 'count']).round(2)

# Rename the aggregated columns for clarity
r.columns = ['Avg', 'Median', 'Count']

# Print the resulting salary benchmarks by department and currency
print(r)

                                      Avg    Median  Count
department             currency
Engineering            GBP       43580.12  40632.98     10
                       USD       30850.90  34329.59      5
                       ZAR       33195.09  35917.80     12
Finance                GBP       31096.12  31719.41      5
                       USD       87676.22  38597.70      7
                       ZAR       37262.52  37390.04      6
Human Resources        GBP       36016.42  29455.62     10
                       USD       54174.53  31567.02     14
                       ZAR       58245.97  32685.73     15
Information Technology GBP       35309.93  33736.00      8
                       USD       36616.06  38540.35      8
                       ZAR       34501.39  31608.38     13
Operations             GBP       28019.71  20549.36      5
                       USD       34355.64  31544.19      5
                       ZAR       32939.54  31286.28      7
Sales                  GBP       25249.97  26916.26      5
                       USD       35982.63  37847.62      5
                       ZAR       32720.59  32863.20     10

In [53]:
# KPI — Median Tenure of Active Employees 

# Capture the current date as a pandas Timestamp for tenure calculations
today = pd.Timestamp(datetime.today())

# Calculate tenure in days for each employee, using exit_date if present, else today
df['tenure_days'] = df.apply(
    lambda r: (r['exit_date'] - r['hire_date']).days
              if pd.notna(r['exit_date'])
              else (today - r['hire_date']).days,
    axis=1
)

# Select only active employees for separate tenure reporting
at = df[df['is_active'] == True]['tenure_days']

# Print summary statistics: median, mean, min, max (median also converted to years)
print(
    f"Median: {at.median():.0f}d ({at.median()/365.25:.1f}y) | "
    f"Mean: {at.mean():.0f}d | "
    f"Min: {at.min():.0f}d | "
    f"Max: {at.max():.0f}d"
)

Median: 2584d (7.1y) | Mean: 2582d | Min: 1168d | Max: 3991d

In [54]:
#  KPI — Overall Employee Turnover Rate 

# Count how many employees have a non-null exit_date (i.e., have left)
e = df['exit_date'].notna().sum()   

# Count the total number of employee records
t = len(df)                          

# Print the total exited, total employees, and the cumulative turnover rate as a percentage
print(f"Exited: {e} | Total: {t} | Turnover: {e / t * 100:.2f}%")

Exited: 46 | Total: 150 | Turnover: 30.67%

In [55]:
#  KPI — Top 5 Managers by Direct Report Count 

# Loop through the top 5 most-referenced manager_ids and their employee counts
for mid, c in df['manager_id'].value_counts().head(5).items():

    # Find the row in df where employee_id matches this manager_id
    r = df[df['employee_id'] == mid]

    # Construct the manager's full name; fallback to '(not found)' if no match
    n = (
        f"{r.iloc[0]['first_name']} {r.iloc[0]['last_name']}"
        if not r.empty
        else "(not found)"
    )

    # Print manager_id, name, and the number of direct reports
    print(f"  {int(mid)}: {n} — {c} reports")

  1006: Esi Dlamini — 7 reports
  1003: Oscar Mthembu — 5 reports
  1001: Ken Naidoo — 4 reports
  1016: Ken Khan — 4 reports
  1021: Que Brown — 3 reports

In [5]:
from IPython.display import HTML, display

# Load Google Fonts — same typography as the cover page for consistency
display(HTML('<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@300;400;500&family=Source+Sans+3:wght@300;400;500;600&display=swap" rel="stylesheet">'))

# Hide the code cell after execution so only the visual output shows
display(HTML('<style>.jp-Cell.jp-CodeCell:has(.cell-closing-output) .jp-Cell-inputWrapper,\
.cell.code_cell:has(.cell-closing-output) .input{display:none !important;}</style>'))

display(HTML("""
<div class="cell-closing-output" style="
    background: linear-gradient(145deg, #f5eeff 0%, #e8d6f7 40%, #d4b8ee 70%, #ede0fa 100%);
    border-radius: 24px;
    padding: 56px 48px 48px;
    position: relative;
    overflow: hidden;
    box-shadow: 0 30px 80px rgba(74,31,138,0.25), 0 8px 24px rgba(0,0,0,0.15);
    max-width: 780px;
    margin: auto;
    font-family: 'Source Sans 3', sans-serif;
">

    <!-- Ambient light overlays -->
    <div style="position:absolute; top:0; right:0; bottom:0; left:0;
        background:
            radial-gradient(ellipse 60% 50% at 90% 10%, rgba(255,255,255,0.55) 0%, transparent 60%),
            radial-gradient(ellipse 40% 40% at 5% 90%, rgba(190,159,225,0.3) 0%, transparent 60%);
        pointer-events:none;">
    </div>

    <!-- Decorative orb: top-right -->
    <div style="position:absolute; width:180px; height:180px; top:-60px; right:-50px;
        border-radius:50%;
        background: radial-gradient(circle, rgba(107,47,175,0.12) 0%, transparent 70%);
        border:1px solid rgba(107,47,175,0.08); pointer-events:none;">
    </div>

    <!-- Decorative orb: bottom-right -->
    <div style="position:absolute; width:120px; height:120px; bottom:60px; right:40px;
        border-radius:50%;
        background: radial-gradient(circle, rgba(190,159,225,0.10) 0%, transparent 70%);
        border:1px solid rgba(190,159,225,0.12); pointer-events:none;">
    </div>

    <!-- Decorative orb: mid-left -->
    <div style="position:absolute; width:80px; height:80px; top:50%; left:-20px;
        border-radius:50%;
        background: radial-gradient(circle, rgba(107,47,175,0.08) 0%, transparent 70%);
        pointer-events:none;">
    </div>

    <!-- Top accent bar -->
    <div style="position:absolute; top:0; left:0; right:0; height:3px;
        background: linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);
    "></div>

    <!-- Header block — fully centred -->
    <div style="text-align:center; margin-bottom:36px; position:relative;">

        <!-- Centred eyebrow label -->
        <p style="font-family:'Source Sans 3',sans-serif; font-size:10px; font-weight:600;
            letter-spacing:7px; text-transform:uppercase; color:#7b4db5;
            margin:0 0 18px 0; text-align:center;">
            Week 3 Project &nbsp;|&nbsp; Data Cleaning &amp; Preparation
        </p>

        <!-- Main title — centred -->
        <h1 style="font-family:'Playfair Display',serif; font-size:52px; font-weight:400;
            color:#2a0f5e; letter-spacing:3px; line-height:1.1;
            margin:0 0 14px 0; text-align:center;">
            Project <span style="color:#6b2faf;">Complete</span>
        </h1>

        <!-- Group Excel | February 2026 — centred directly under title -->
        <p style="font-family:'Source Sans 3',sans-serif; font-size:11px; font-weight:600;
            letter-spacing:6px; text-transform:uppercase; color:#9b70cc;
            margin:0; text-align:center;">
            Group Excel &nbsp;|&nbsp; February 2026
        </p>

        <!-- Thin centred rule -->
        <div style="width:60px; height:1px;
            background: linear-gradient(90deg, transparent, rgba(107,47,175,0.4), transparent);
            margin:24px auto 0;">
        </div>

    </div>

    <!-- Info card -->
    <div style="
        background:
            radial-gradient(ellipse at 15% 10%, rgba(180,150,230,0.14) 0%, transparent 50%),
            radial-gradient(ellipse at 85% 90%, rgba(90,50,150,0.10) 0%, transparent 50%),
            radial-gradient(ellipse at 50% 50%, rgba(140,100,210,0.06) 0%, transparent 60%),
            linear-gradient(150deg,
                #6b3fa0 0%,
                #7344a8 10%,
                #7b4db5 25%,
                #8254bc 38%,
                #8a5ac2 50%,
                #8254bc 62%,
                #7b4db5 75%,
                #7344a8 90%,
                #7040aa 100%);
        border-radius:16px;
        padding:36px 40px;
        border:1px solid rgba(255,255,255,0.18);
        box-shadow:
            0 30px 70px rgba(74,31,138,0.40),
            0 12px 28px rgba(0,0,0,0.20),
            0 4px 10px rgba(74,31,138,0.15),
            inset 0 1px 0 rgba(255,255,255,0.18),
            inset 0 -1px 0 rgba(0,0,0,0.12);
        position:relative;
        overflow:hidden;
    ">

        <!-- Card inner glow: top-right -->
        <div style="position:absolute; top:-30px; right:-30px; width:200px; height:200px;
            background: radial-gradient(circle, rgba(200,175,240,0.12) 0%, transparent 70%);
            border-radius:50%; pointer-events:none;">
        </div>

        <!-- Card inner glow: bottom-left -->
        <div style="position:absolute; bottom:-25px; left:-25px; width:170px; height:170px;
            background: radial-gradient(circle, rgba(90,50,150,0.08) 0%, transparent 70%);
            border-radius:50%; pointer-events:none;">
        </div>

        <!-- Card top shine line -->
        <div style="position:absolute; top:0; left:20px; right:20px; height:1px;
            background: linear-gradient(90deg, transparent, rgba(255,255,255,0.20) 25%, rgba(255,255,255,0.38) 50%, rgba(255,255,255,0.20) 75%, transparent);
        "></div>

        <!-- GROUP label + badge -->
        <p style="font-family:'Source Sans 3',sans-serif; font-size:9px; font-weight:600;
            letter-spacing:5px; text-transform:uppercase; color:rgba(255,255,255,0.6);
            margin:0 0 10px 0;">
            Group
        </p>

        <div style="display:inline-flex; align-items:center; gap:10px;
            background:rgba(255,255,255,0.12); border:1px solid rgba(255,255,255,0.25);
            border-radius:8px; padding:8px 18px; margin-bottom:24px;">
            <div style="width:6px; height:6px; border-radius:50%; background:#fff;
                box-shadow:0 0 8px rgba(255,255,255,0.7);"></div>
            <span style="font-family:'Source Sans 3',sans-serif; font-size:18px; font-weight:700;
                letter-spacing:6px; color:#ffffff;">EXCEL</span>
        </div>

        <!-- Divider -->
        <div style="height:1px;
            background:linear-gradient(90deg, rgba(255,255,255,0.2), rgba(255,255,255,0.05));
            margin-bottom:24px;">
        </div>

        <!-- MEMBERS label + pills -->
        <p style="font-family:'Source Sans 3',sans-serif; font-size:9px; font-weight:600;
            letter-spacing:5px; text-transform:uppercase; color:rgba(255,255,255,0.6);
            margin:0 0 12px 0;">
            Members
        </p>

        <div style="display:flex; flex-wrap:wrap; gap:10px; margin-bottom:24px;">
            <span style="font-family:'Source Sans 3',sans-serif; font-size:13px; color:#fff;
                background:rgba(255,255,255,0.12); border:1px solid rgba(255,255,255,0.22);
                border-radius:30px; padding:5px 16px;">Lebogang</span>
            <span style="font-family:'Source Sans 3',sans-serif; font-size:13px; color:#fff;
                background:rgba(255,255,255,0.12); border:1px solid rgba(255,255,255,0.22);
                border-radius:30px; padding:5px 16px;">Sibongile</span>
            <span style="font-family:'Source Sans 3',sans-serif; font-size:13px; color:#fff;
                background:rgba(255,255,255,0.12); border:1px solid rgba(255,255,255,0.22);
                border-radius:30px; padding:5px 16px;">Tersh</span>
            <span style="font-family:'Source Sans 3',sans-serif; font-size:13px; color:#fff;
                background:rgba(255,255,255,0.12); border:1px solid rgba(255,255,255,0.22);
                border-radius:30px; padding:5px 16px;">Tshepang</span>
            <span style="font-family:'Source Sans 3',sans-serif; font-size:13px; color:#fff;
                background:rgba(255,255,255,0.12); border:1px solid rgba(255,255,255,0.22);
                border-radius:30px; padding:5px 16px;">Lethukuthula</span>
        </div>

        <!-- Divider -->
        <div style="height:1px;
            background:linear-gradient(90deg, rgba(255,255,255,0.2), rgba(255,255,255,0.05));
            margin-bottom:24px;">
        </div>

        <!-- Stats row: Phases | Cells | Output -->
        <div style="display:flex; gap:0; flex-wrap:wrap;">

            <!-- Phases -->
            <div style="flex:1; min-width:140px; padding-right:24px; position:relative;">
                <p style="font-family:'Source Sans 3',sans-serif; font-size:9px; font-weight:600;
                    letter-spacing:4px; text-transform:uppercase; color:rgba(255,255,255,0.6);
                    margin:0 0 6px 0;">Phases</p>
                <p style="font-family:'Source Sans 3',sans-serif; font-size:22px; font-weight:300;
                    color:#fff; margin:0 0 4px 0;">9</p>
                <p style="font-family:'Source Sans 3',sans-serif; font-size:11px;
                    color:rgba(255,255,255,0.6); margin:0;">Setup through KPIs</p>
                <div style="position:absolute; right:0; top:0; bottom:0; width:1px;
                    background:linear-gradient(180deg, transparent, rgba(255,255,255,0.2), transparent);">
                </div>
            </div>

            <!-- Cells -->
            <div style="flex:1; min-width:140px; padding:0 24px; position:relative;">
                <p style="font-family:'Source Sans 3',sans-serif; font-size:9px; font-weight:600;
                    letter-spacing:4px; text-transform:uppercase; color:rgba(255,255,255,0.6);
                    margin:0 0 6px 0;">Cells</p>
                <p style="font-family:'Source Sans 3',sans-serif; font-size:22px; font-weight:300;
                    color:#fff; margin:0 0 4px 0;">65</p>
                <p style="font-family:'Source Sans 3',sans-serif; font-size:11px;
                    color:rgba(255,255,255,0.6); margin:0;">Markdown and Code</p>
                <div style="position:absolute; right:0; top:0; bottom:0; width:1px;
                    background:linear-gradient(180deg, transparent, rgba(255,255,255,0.2), transparent);">
                </div>
            </div>

            <!-- Output -->
            <div style="flex:1; min-width:140px; padding-left:24px;">
                <p style="font-family:'Source Sans 3',sans-serif; font-size:9px; font-weight:600;
                    letter-spacing:4px; text-transform:uppercase; color:rgba(255,255,255,0.6);
                    margin:0 0 6px 0;">Output</p>
                <p style="font-family:'Source Sans 3',sans-serif; font-size:22px; font-weight:300;
                    color:#fff; margin:0 0 4px 0;">CSV</p>
                <p style="font-family:'Source Sans 3',sans-serif; font-size:11px;
                    color:rgba(255,255,255,0.6); margin:0;">Employee-Data_CLEANED</p>
            </div>

        </div>

    </div>

    <!-- Bottom accent bar -->
    <div style="position:absolute; bottom:0; left:0; right:0; height:3px;
        background: linear-gradient(90deg, transparent, #c8a8e8 15%, #6b2faf 35%, #3b1278 50%, #6b2faf 65%, #c8a8e8 85%, transparent);
    "></div>

</div>
"""))